import React, { createContext, useContext, useState, useMemo } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    home: "Home",
    dashboard: "Dashboard",
    myFarms: "My Farms",
    cropAdvice: "Crop Advice",
    pestControl: "Pest Control",
    marketPrices: "Market Prices",
    welcomeToKrishiGyan: "Welcome to KrishiGyan",
    smartFarmingAssistant: "Your Smart Farming Assistant",
    empowerYourFarming:
      "Empower your farming journey with AI-powered insights and expert guidance",
    getStarted: "Get Started",
    aiPoweredAdvice: "AI-Powered Crop Advice",
    getPersonalizedCropAdvice:
      "Get personalized crop recommendations based on soil, weather, and market conditions",
    exploreCrops: "Explore Crops",
    stayUpdated: "Stay Updated",
    trackMarketPrices:
      "Track real-time agricultural commodity prices and make informed selling decisions",
    viewPrices: "View Prices",
    quickAccess: "Quick Access",
    manageYourFarms: "Manage and track your farm activities",
    managePests: "Identify and manage agricultural pests",
    viewMarketPrices: "View real-time commodity prices",
    governmentSchemes: "Government Schemes",
    applyForSchemes: "Apply for subsidies and benefits",
    platformStats: "Platform Statistics",
    activeFarmers: "Active Farmers",
    cropVarieties: "Crop Varieties",
    aiSupport: "AI Support",
    latestNews: "Latest News & Updates",
    viewAll: "View All",
    news1Title: "New Organic Farming Scheme Launched",
    news1Excerpt:
      "Government announces new subsidies for organic farming practices. Apply now!",
    news2Title: "Monsoon Forecast: Above Normal Rainfall Expected",
    news2Excerpt:
      "IMD predicts above normal rainfall for Kerala this monsoon season.",
    news3Title: "Coconut Prices Reach All-Time High",
    news3Excerpt: "Coconut prices surge to ₹45 per kg in major Kerala markets.",
    news4Title: "AI Chatbot Now Available in Malayalam",
    news4Excerpt:
      "Our AI assistant now supports full Malayalam language for better communication.",
    schemes: "Schemes",
    updates: "Updates",
    announcements: "Announcements",
    announcement1: "New crop insurance scheme registration open",
    announcement2: "Weather alert: Heavy rain expected this week",
    announcement3: "Market prices updated daily at 9 AM",
    quickLinks: "Quick Links",
    aboutUs: "About KrishiGyan",
    ourMission: "Our Mission",
    missionText:
      "KrishiGyan is dedicated to empowering farmers with cutting-edge technology and AI-powered solutions. We aim to revolutionize farming practices by providing real-time insights, expert guidance, and comprehensive tools for modern agriculture.",
    ourVision: "Our Vision",
    visionText:
      "To become the leading digital platform for farmers, helping them make informed decisions, increase productivity, and achieve sustainable farming practices through technology.",
    whatWeOffer: "What We Offer",
    offer1: "AI-powered crop recommendations",
    offer2: "Real-time market price tracking",
    offer3: "Pest and disease identification",
    offer4: "Government scheme information",
    offer5: "Farm expense and profit tracking",
    offer6: "Task scheduling and calendar management",
    offer7: "24/7 AI chatbot support",
    offer8: "Multi-language support",
    contactUs: "Contact Us",
    thankYou: "Thank You!",
    contactSubmitted:
      "Your message has been submitted successfully. We will get back to you soon.",
    sendAnother: "Send Another Message",
    fullName: "Full Name",
    email: "Email",
    phoneNumber: "Phone Number",
    subject: "Subject",
    message: "Message",
    sendMessage: "Send Message",
    getInTouch: "Get In Touch",
    phone: "Phone",
    address: "Address",
    addressLine1: "KrishiGyan Headquarters",
    addressLine2: "Kerala Agricultural Technology Park",
    addressLine3: "Thiruvananthapuram, Kerala - 695001",
    addressLine4: "India",
    followUs: "Follow Us",
    needHelp: "Need Help?",
    helpText:
      "Our support team is available 24/7 to assist you with any questions or issues.",
    faq: "Frequently Asked Questions",
    userGuide: "User Guide & Tutorials",
    farmExpenses: "Farm Expenses",
    farmExpensesProfit: "Farm Expenses & Profit Calculator",
    trackExpensesCalculateProfit:
      "Track your farm expenses and calculate your profit",
    addExpense: "Add Expense",
    category: "Category",
    selectCategory: "Select Category",
    item: "Item",
    itemPlaceholder: "e.g., Rice Seeds, Urea Fertilizer",
    amount: "Amount (₹)",
    date: "Date",
    description: "Description",
    descriptionPlaceholder: "Additional notes...",
    income: "Income",
    cropSales: "Crop Sales (₹)",
    otherIncome: "Other Income (₹)",
    totalExpenses: "Total Expenses",
    totalIncome: "Total Income",
    profit: "Profit",
    profitMargin: "Profit Margin",
    expenseList: "Expense List",
    exportCSV: "Export CSV",
    noExpensesYet: "No expenses added yet",
    addFirstExpense: "Add your first expense to start tracking",
    actions: "Actions",
    delete: "Delete",
    total: "Total",
    expensesByCategory: "Expenses by Category",
    expenseReport: "Expense Report",
    fillAllFields: "Please fill all required fields",
    expenseCategorySeeds: "Seeds",
    expenseCategoryFertilizers: "Fertilizers",
    expenseCategoryPesticides: "Pesticides",
    expenseCategoryLabor: "Labor",
    expenseCategoryEquipment: "Equipment",
    expenseCategoryIrrigation: "Irrigation",
    expenseCategoryTransport: "Transport",
    expenseCategoryLandRent: "Land Rent",
    expenseCategoryOther: "Other",
    farmCalendar: "Farm Calendar",
    farmCalendarTaskScheduler: "Farm Calendar & Task Scheduler",
    scheduleManageTasks: "Schedule and manage your farming tasks",
    addTask: "Add Task",
    editTask: "Edit Task",
    updateTask: "Update Task",
    taskTitle: "Task Title",
    time: "Time",
    priority: "Priority",
    priorityLow: "Low",
    priorityMedium: "Medium",
    priorityHigh: "High",
    status: "Status",
    statusPending: "Pending",
    statusInProgress: "In Progress",
    statusCompleted: "Completed",
    taskCategoryPlanting: "Planting",
    taskCategoryHarvesting: "Harvesting",
    taskCategoryIrrigation: "Irrigation",
    taskCategoryFertilizing: "Fertilizing",
    taskCategoryPestControl: "Pest Control",
    taskCategoryPruning: "Pruning",
    taskCategoryWeeding: "Weeding",
    taskCategoryOther: "Other",
    tasksFor: "Tasks for",
    noTasksForDate: "No tasks for this date",
    upcomingTasks: "Upcoming Tasks",
    noUpcomingTasks: "No upcoming tasks",
    filter: "Filter",
    allCategories: "All Categories",
    allStatuses: "All Statuses",
    fillRequiredFields: "Please fill all required fields",
    confirmDeleteTask: "Are you sure you want to delete this task?",
    monthJanuary: "January",
    monthFebruary: "February",
    monthMarch: "March",
    monthApril: "April",
    monthMay: "May",
    monthJune: "June",
    monthJuly: "July",
    monthAugust: "August",
    monthSeptember: "September",
    monthOctober: "October",
    monthNovember: "November",
    monthDecember: "December",
    daySunday: "Sun",
    dayMonday: "Mon",
    dayTuesday: "Tue",
    dayWednesday: "Wed",
    dayThursday: "Thu",
    dayFriday: "Fri",
    daySaturday: "Sat",
    logout: "Logout",
    signInToYourAccount: "Sign in to your account",
    signIn: "Sign In",
    signingIn: "Signing In...",
    dontHaveAccount: "Don't have an account?",
    signUpHere: "Sign up here",
    createFarmerAccount: "Create your farmer account",
    createAccount: "Create Account",
    creatingAccount: "Creating Account...",
    alreadyHaveAccount: "Already have an account?",
    signInHere: "Sign in here",
    welcomeBack: "Welcome back,",
    farmingOverview: "Here's your farming overview for today",
    totalFarms: "Total Farms",
    weather: "Weather",
    activeCrops: "Active Crops",
    loadingFarmData: "Loading your farm data...",
    pestControlCardTitle: "Pest Control",
    pestControlCardSubtitle: "Identify & manage pests",
    marketPricesCardTitle: "Market Prices",
    marketPricesCardSubtitle: "Check current rates",
    weatherIn: "Weather in",
    humidity: "Humidity",
    rainfall: "Rainfall",
    quickActions: "Quick Actions",
    manageFarms: "Manage Farms",
    addNewFarm: "Add New Farm",
    yourFarms: "Your Farms",
    noFarmsYet: "No farms yet",
    addFirstFarmText:
      "Add your first farm to get started with crop recommendations",
    addFirstFarmButton: "Add Your First Farm",
    emailPlaceholder: "Enter your email",
    passwordPlaceholder: "Enter your password",
    fullNamePlaceholder: "Full Name",
    emailAddressPlaceholder: "Email Address",
    phoneNumberPlaceholder: "Phone Number",
    selectDistrictPlaceholder: "Select District",
    villagePlaceholder: "Village/Town",
    createPasswordPlaceholder: "Create Password",
    languageEnglish: "English",
    languageMalayalam: "Malayalam",
    languageTamil: "Tamil",
    languageKannada: "Kannada",
    languageTulu: "Tulu",
    languageKonkani: "Konkani",
    languageHindi: "Hindi",
    languageUrdu: "Urdu",
    languageLabelShort: "Language",
    // Farms
    farmsTitle: "My Farms",
    farmsSubtitle: "Manage your agricultural lands",
    addFarmButton: "Add Farm",
    editFarmTitle: "Edit Farm",
    addNewFarmTitle: "Add New Farm",
    farmNameLabel: "Farm Name",
    farmNamePlaceholder: "Enter farm name",
    locationLabel: "Location",
    locationPlaceholder: "District, Village",
    cropTypeLabel: "Crop Type",
    cropTypePlaceholder: "Select Crop (Optional)",
    farmSizeLabel: "Farm Size",
    sizePlaceholder: "Size",
    acres: "Acres",
    hectares: "Hectares",
    cancel: "Cancel",
    saving: "Saving...",
    saveFarm: "Save Farm",
    updateFarm: "Update Farm",
    addFarm: "Add Farm",
    noFarmsAddedTitle: "No farms added yet",
    noFarmsAddedText:
      "Add your first farm to start getting agricultural advice",
    addFirstFarmButtonFarms: "Add Your First Farm",
    deleteFarmConfirm: "Are you sure you want to delete this farm?",
    // Crop Recommendations
    cropRecoTitle: "Crop Recommendations",
    cropRecoSubtitle:
      "Get AI-powered crop suggestions based on your farm conditions",
    farmConditions: "Farm Conditions",
    soilTypeLabel: "Soil Type",
    waterAvailabilityLabel: "Water Availability",
    districtOptionalLabel: "District (Optional)",
    districtPlaceholderReco: "Enter your district",
    analyzeButton: "Get Crop Recommendations",
    analyzingText: "Analyzing Farm Conditions...",
    analyzingSpinnerText: "Analyzing your farm conditions...",
    noRecoTitle: "No recommendations found",
    noRecoText: "Try adjusting your farm conditions for better results",
    recommendedCropsTitle: "Recommended Crops",
    seasonLabel: "Season",
    waterLabel: "Water",
    durationLabel: "Duration",
    yieldLabel: "Yield",
    benefitsLabel: "Benefits:",
    suitabilityHigh: "Highly Suitable",
    suitabilitySuitable: "Suitable",
    suitabilityModerate: "Moderately Suitable",
    suitabilityLow: "Less Suitable",
    // Market Prices
    marketTitle: "Kerala Agricultural Market Prices",
    marketSubtitle: "Real-time commodity prices across Kerala markets",
    commoditiesLabel: "Commodities",
    marketsLabel: "Markets",
    avgPriceLabel: "Avg Price",
    risingPricesLabel: "Rising Prices",
    filterPricesTitle: "Filter Prices",
    searchLabel: "Search Commodities & Markets",
    searchPlaceholder: "Search rice, coconut, market names...",
    selectCommodityLabel: "Select Commodity",
    allCommoditiesOption: "All Commodities",
    selectDistrictLabel: "Select District",
    refreshPricesButton: "Refresh Prices",
    refreshingButton: "Refreshing...",
    exportCsvButton: "Export as CSV",
    clearFiltersButton: "Clear Filters",
    marketTrendsTitle: "Market Trends",
    marketInsightTitle: "Market Insight:",
    marketInsightText:
      "Prices update daily from government APMC markets. Check regularly for best selling times.",
    sellingTipsTitle: "Selling Tips",
    sellingTips1: "Sell in morning hours for better prices",
    sellingTips2: "Check multiple market rates",
    sellingTips3: "Grade your produce for premium pricing",
    sellingTips4: "Monitor weekly price trends",
    sellingTips5: "Consider government procurement schemes",
    marketPriceListTitle: "Market Price List",
    showingCommoditiesText: "Showing",
    inText: "in",
    dateLabel: "Date",
    loadingMarketTitle: "Loading Market Prices",
    loadingMarketText: "Fetching latest prices from Kerala markets...",
    commodityColumn: "Commodity",
    marketColumn: "Market",
    districtColumn: "District",
    priceRangeColumn: "Price Range",
    trendColumn: "Trend",
    updatedColumn: "Updated",
    perUnitText: "per",
    noMarketDataText:
      "No market data found for your filters. Try different selection.",
    tableFooterSource:
      "Data sourced from Agmarknet & Kerala Agricultural Department",
    tableFooterShowing: "Showing",
    tableFooterOf: "of",
    tableFooterEntries: "entries",
    refreshButton: "Refresh",
    dataSourcesTitle: "Data Sources & Updates",
    agmarknetStatus: "Agmarknet API:",
    agmarknetConnected: "Connected",
    agmarknetOffline: "Offline",
    updatesEvery: "Updates: Every 5 minutes",
    coverageLabel: "Coverage:",
    nextUpdateText: "Next update in 5 minutes",
    priceAlertsTitle: "Price Alerts",
    priceAlertsText: "Get notified when your crop prices reach target levels",
    setPriceAlertButton: "Set Price Alert",
    priceAlertPrompt: "Set price alert for",
    priceAlertCurrent: "Current price",
    priceAlertEnterTarget: "Enter target price (₹ per kg):",
    priceAlertSuccess: "Price alert set!",
    nearestMarketsTitle: "Nearest Markets",
    nearestMarketsText: "Find Agricultural Produce Market Committees near you",
    viewMapButton: "View Map",
    // Pest Management (Plant Health)
    plantIdOnline: "Plant.id v3 AI Online",
    plantIdOffline: "Using Advanced Simulation",
    plantIdChecking: "Testing AI Connection...",
    plantIdStatusOnline: "Real-time disease detection active",
    plantIdStatusOffline: "Advanced image analysis simulation",
    plantIdStatusChecking: "Checking Plant.id v3 API...",
    aiScannerTitle: "AI Plant Health Scanner",
    aiScannerSubtitle:
      "Advanced pest and disease detection using Plant.id v3 AI technology",
    uploadLeafTitle: "Upload Plant Leaf Image",
    uploadLeafSubtitle:
      "Get instant AI-powered diagnosis and treatment recommendations",
    aiAnalysisInProgress: "AI Analysis in Progress...",
    captureOrUpload: "Capture or Upload Leaf Image",
    bestResultsText:
      "For best results: Take clear photo in daylight, focus on affected areas, include multiple leaves if possible",
    selectImageButton: "Select Image",
    analyzingWithAI: "Analyzing with AI...",
    clearImageButton: "Clear Image",
    imagePreviewTitle: "Image Preview",
    readyForAI: "Ready for AI Analysis",
    simulationTitle: "Using Advanced Simulation",
    simulationMessage: "API connection issue - using local analysis",
    technicalInfoTitle: "Technical Info:",
    technicalInfoOnline: "Using Plant.id v3 API for real detection",
    technicalInfoOffline: "Using advanced simulation with image analysis",
    diseaseDetectedTitle: "Disease Detected",
    plantHealthyTitle: "Plant is Healthy",
    aiConfidenceLabel: "AI Confidence",
    diagnosisDetailsTitle: "Diagnosis Details",
    scientificClassificationTitle: "Scientific Classification",
    treatmentTitle: "Recommended Treatment",
    treatmentFooter: "Apply treatment at first signs",
    preventionTitle: "Prevention Measures",
    careRecoTitle: "Plant Care Recommendations",
    analyzeAnotherImageButton: "Analyze Another Image",
    poweredByPlantIdTitle: "Powered by Plant.id v3 API",
    poweredByPlantIdText:
      "Advanced machine learning trained on millions of plant images for accurate disease detection",
    aiPoweredTitle: "AI-Powered",
    aiPoweredText: "Uses Plant.id v3 neural networks",
    globalDatabaseTitle: "Global Database",
    globalDatabaseText: "Thousands of plant species",
    realtimeTitle: "Real-time",
    realtimeText: "Instant analysis and results",
    plantIdFooter: "Using Plant.id v3 API for plant disease detection",
    // Chatbot
    chatbotFloatingTooltip: "Farmers Assistant",
    chatbotHeaderTitle: "Farmers Assistant",
    chatbotHeaderSubtitle: "Powered by AI",
    chatbotQuickQuestionsTitle: "Quick Questions:",
    chatbotQuick1: "Best crops for this season?",
    chatbotQuick2: "Pest control in paddy fields?",
    chatbotQuick3: "Organic farming schemes",
    chatbotQuick4: "Coconut farming tips",
    chatbotQuick5: "Weather advice",
    chatbotQuick6: "Market prices",
    chatbotThinking: "Thinking",
    chatbotPlaceholder: "Ask about farming in Kerala...",
    chatbotClear: "Clear",
    chatbotPressEnter: "Press Enter to send",
    chatbotError:
      "I apologize, but I'm experiencing technical difficulties. Please try again later.",
    chatbotGreeting:
      "Namaskaram! 🙏 I'm your dedicated Kerala Farmers AI Assistant, powered by Google Gemini AI. I specialize in providing accurate agricultural information for Kerala farmers.\n\nWhat would you like to know about farming in Kerala today?",
  },
  ml: {
    home: "ഹോം",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    myFarms: "എന്റെ ഫാരങ്ങൾ",
    cropAdvice: "വിള നിർദേശങ്ങൾ",
    pestControl: "കീട നിയന്ത്രണം",
    marketPrices: "മാർക്കറ്റ് വിലകൾ",
    welcomeToKrishiGyan: "ക്രിഷിഗ്യാൻ സ്വാഗതം",
    smartFarmingAssistant: "നിങ്ങളുടെ സ്മാർട്ട് കൃഷി അസിസ്റ്റന്റ്",
    empowerYourFarming:
      "AI അധിഷ്ഠിത ഉൾക്കാഴ്ചകളും വിദഗ്ധ മാർഗ്ഗനിർദ്ദേശങ്ങളും ഉപയോഗിച്ച് നിങ്ങളുടെ കൃഷി യാത്ര ശക്തിപ്പെടുത്തുക",
    getStarted: "ആരംഭിക്കുക",
    aiPoweredAdvice: "AI അധിഷ്ഠിത വിള നിർദേശം",
    getPersonalizedCropAdvice:
      "മണ്ണ്, കാലാവസ്ഥ, മാർക്കറ്റ് സാഹചര്യങ്ങൾ അടിസ്ഥാനമാക്കി വ്യക്തിഗത വിള നിർദേശങ്ങൾ നേടുക",
    exploreCrops: "വിളകൾ പര്യവേക്ഷണം ചെയ്യുക",
    stayUpdated: "അപ്ഡേറ്റ് ആയിരിക്കുക",
    trackMarketPrices:
      "തത്സമയ കൃഷി ഉൽപ്പന്ന വിലകൾ ട്രാക്ക് ചെയ്ത് അറിവുള്ള വിൽപ്പന തീരുമാനങ്ങൾ എടുക്കുക",
    viewPrices: "വിലകൾ കാണുക",
    quickAccess: "വേഗത്തിലുള്ള പ്രവേശനം",
    manageYourFarms:
      "നിങ്ങളുടെ ഫാം പ്രവർത്തനങ്ങൾ കൈകാര്യം ചെയ്യുകയും ട്രാക്ക് ചെയ്യുകയും ചെയ്യുക",
    managePests: "കൃഷി കീടങ്ങളെ തിരിച്ചറിയുകയും കൈകാര്യം ചെയ്യുകയും ചെയ്യുക",
    viewMarketPrices: "തത്സമയ ഉൽപ്പന്ന വിലകൾ കാണുക",
    governmentSchemes: "സർക്കാർ സ്കീമുകൾ",
    applyForSchemes: "സബ്സിഡികളും നേട്ടങ്ങളും അപേക്ഷിക്കുക",
    platformStats: "പ്ലാറ്റ്ഫോം സ്ഥിതിവിവരക്കണക്കുകൾ",
    activeFarmers: "സജീവ കർഷകർ",
    cropVarieties: "വിള വ്യതിയാനങ്ങൾ",
    aiSupport: "AI പിന്തുണ",
    latestNews: "ഏറ്റവും പുതിയ വാർത്തകളും അപ്ഡേറ്റുകളും",
    viewAll: "എല്ലാം കാണുക",
    news1Title: "പുതിയ ഓർഗാനിക് കൃഷി സ്കീം ആരംഭിച്ചു",
    news1Excerpt:
      "ഓർഗാനിക് കൃഷി രീതികൾക്ക് പുതിയ സബ്സിഡികൾ സർക്കാർ പ്രഖ്യാപിച്ചു. ഇപ്പോൾ അപേക്ഷിക്കുക!",
    news2Title: "മൺസൂൺ പ്രവചനം: സാധാരണത്തിലും കൂടുതൽ മഴ പ്രതീക്ഷിക്കുന്നു",
    news2Excerpt:
      "ഈ മൺസൂൺ സീസണിൽ കേരളത്തിൽ സാധാരണത്തിലും കൂടുതൽ മഴ ലഭിക്കുമെന്ന് IMD പ്രവചിക്കുന്നു.",
    news3Title: "തേങ്ങ വില എല്ലാ കാലത്തെയും ഉയർന്ന നിലയിലെത്തി",
    news3Excerpt:
      "കേരളത്തിലെ പ്രധാന മാർക്കറ്റുകളിൽ തേങ്ങ വില കിലോയ്ക്ക് ₹45 എന്ന നിലയിലെത്തി.",
    news4Title: "AI ചാറ്റ്ബോട്ട് ഇപ്പോൾ മലയാളത്തിൽ ലഭ്യമാണ്",
    news4Excerpt:
      "മികച്ച ആശയവിനിമയത്തിനായി ഞങ്ങളുടെ AI അസിസ്റ്റന്റ് ഇപ്പോൾ പൂർണ്ണ മലയാളം പിന്തുണയ്ക്കുന്നു.",
    schemes: "സ്കീമുകൾ",
    updates: "അപ്ഡേറ്റുകൾ",
    announcements: "പ്രഖ്യാപനങ്ങൾ",
    announcement1: "പുതിയ വിള ഇൻഷുറൻസ് സ്കീം രജിസ്ട്രേഷൻ തുറന്നു",
    announcement2: "കാലാവസ്ഥ അലർട്ട്: ഈ ആഴ്ച ശക്തമായ മഴ പ്രതീക്ഷിക്കുന്നു",
    announcement3:
      "മാർക്കറ്റ് വിലകൾ ദിവസം തോറും രാവിലെ 9 മണിക്ക് അപ്ഡേറ്റ് ചെയ്യുന്നു",
    quickLinks: "വേഗത്തിലുള്ള ലിങ്കുകൾ",
    aboutUs: "ക്രിഷിഗ്യാൻ എന്ന നമ്മളെക്കുറിച്ച്",
    ourMission: "ഞങ്ങളുടെ ലക്ഷ്യം",
    missionText:
      "കർഷകരെ ആധുനിക സാങ്കേതികവിദ്യയും AI അധിഷ്ഠിത പരിഹാരങ്ങളും ഉപയോഗിച്ച് ശക്തിപ്പെടുത്തുക എന്നതാണ് ക്രിഷിഗ്യാന്റെ ലക്ഷ്യം. തത്സമയ ഉൾക്കാഴ്ചകൾ, വിദഗ്ധ മാർഗ്ഗനിർദ്ദേശങ്ങൾ, ആധുനിക കൃഷിക്ക് ആവശ്യമായ സമഗ്ര ഉപകരണങ്ങൾ നൽകി കൃഷി രീതികളിൽ വിപ്ലവം സൃഷ്ടിക്കാൻ ഞങ്ങൾ ലക്ഷ്യമിടുന്നു.",
    ourVision: "ഞങ്ങളുടെ ദർശനം",
    visionText:
      "കർഷകർക്ക് അറിവുള്ള തീരുമാനങ്ങൾ എടുക്കാനും ഉൽപാദനക്ഷമത വർദ്ധിപ്പിക്കാനും സാങ്കേതികവിദ്യയിലൂടെ സുസ്ഥിര കൃഷി പ്രക്രിയകൾ നേടാനും സഹായിക്കുന്ന മുൻനിര ഡിജിറ്റൽ പ്ലാറ്റ്ഫോം ആകുക എന്നതാണ് ഞങ്ങളുടെ ലക്ഷ്യം.",
    whatWeOffer: "ഞങ്ങൾ നൽകുന്നത്",
    offer1: "AI അധിഷ്ഠിത വിള നിർദേശങ്ങൾ",
    offer2: "തത്സമയ മാർക്കറ്റ് വില ട്രാക്കിംഗ്",
    offer3: "കീട-രോഗ തിരിച്ചറിയൽ",
    offer4: "സർക്കാർ സ്കീം വിവരങ്ങൾ",
    offer5: "ഫാം ചെലവും ലാഭ ട്രാക്കിംഗും",
    offer6: "ടാസ്ക് ഷെഡ്യൂളിംഗും കലണ്ടർ മാനേജ്മെന്റും",
    offer7: "24/7 AI ചാറ്റ്ബോട്ട് പിന്തുണ",
    offer8: "മൾട്ടി-ലാംഗ്വേജ് പിന്തുണ",
    contactUs: "ഞളുമായി ബന്ധപ്പെടുക",
    thankYou: "നന്ദി!",
    contactSubmitted:
      "നിങ്ങളുടെ സന്ദേശം വിജയകരമായി സമർപ്പിച്ചു. ഞങ്ങൾ ഉടൻ തന്നെ നിങ്ങളുമായി ബന്ധപ്പെടും.",
    sendAnother: "മറ്റൊരു സന്ദേശം അയയ്ക്കുക",
    fullName: "പൂർണ്ണ പേര്",
    email: "ഇമെയിൽ",
    phoneNumber: "ഫോൺ നമ്പർ",
    subject: "വിഷയം",
    message: "സന്ദേശം",
    sendMessage: "സന്ദേശം അയയ്ക്കുക",
    getInTouch: "ബന്ധപ്പെടുക",
    phone: "ഫോൺ",
    address: "വിലാസം",
    addressLine1: "ക്രിഷിഗ്യാൻ ആസ്ഥാനം",
    addressLine2: "കേരള കൃഷി സാങ്കേതിക പാർക്ക്",
    addressLine3: "തിരുവനന്തപുരം, കേരളം - 695001",
    addressLine4: "ഇന്ത്യ",
    followUs: "ഞങ്ങളെ പിന്തുടരുക",
    needHelp: "സഹായം വേണോ?",
    helpText:
      "എന്തെങ്കിലും ചോദ്യങ്ങൾക്കോ പ്രശ്നങ്ങൾക്കോ 24/7 സഹായിക്കാൻ ഞങ്ങളുടെ സപ്പോർട്ട് ടീം തയ്യാറാണ്.",
    faq: "പതിവ് ചോദ്യങ്ങൾ",
    userGuide: "യൂസർ ഗൈഡ് & ട്യൂട്ടോറിയലുകൾ",
    farmExpenses: "ഫാം ചെലവുകൾ",
    farmExpensesProfit: "ഫാം ചെലവുകളും ലാഭ കാൽക്കുലേറ്ററും",
    trackExpensesCalculateProfit:
      "നിങ്ങളുടെ ഫാം ചെലവുകൾ ട്രാക്ക് ചെയ്ത് ലാഭം കണക്കാക്കുക",
    addExpense: "ചെലവ് ചേർക്കുക",
    category: "വിഭാഗം",
    selectCategory: "വിഭാഗം തിരഞ്ഞെടുക്കുക",
    item: "ഇനം",
    itemPlaceholder: "ഉദാ: അരി വിത്ത്, യൂറിയ എരുമ",
    amount: "തുക (₹)",
    date: "തീയതി",
    description: "വിവരണം",
    descriptionPlaceholder: "അധിക കുറിപ്പുകൾ...",
    income: "വരുമാനം",
    cropSales: "വിള വിൽപ്പന (₹)",
    otherIncome: "മറ്റ് വരുമാനം (₹)",
    totalExpenses: "ആകെ ചെലവുകൾ",
    totalIncome: "ആകെ വരുമാനം",
    profit: "ലാഭം",
    profitMargin: "ലാഭ മാർജിൻ",
    expenseList: "ചെലവ് പട്ടിക",
    exportCSV: "CSV എക്‌സ്‌പോർട്ട് ചെയ്യുക",
    noExpensesYet: "ഇനിയും ചെലവുകൾ ചേർത്തിട്ടില്ല",
    addFirstExpense: "ട്രാക്കിംഗ് ആരംഭിക്കാൻ ആദ്യ ചെലവ് ചേർക്കുക",
    actions: "പ്രവർത്തനങ്ങൾ",
    delete: "ഡിലീറ്റ് ചെയ്യുക",
    total: "ആകെ",
    expensesByCategory: "വിഭാഗം അനുസരിച്ച് ചെലവുകൾ",
    expenseReport: "ചെലവ് റിപ്പോർട്ട്",
    fillAllFields: "ദയവായി എല്ലാ ആവശ്യമായ ഫീൽഡുകളും പൂരിപ്പിക്കുക",
    expenseCategorySeeds: "വിത്തുകൾ",
    expenseCategoryFertilizers: "എരുമകൾ",
    expenseCategoryPesticides: "കീടനാശിനികൾ",
    expenseCategoryLabor: "ജോലിക്കാര്",
    expenseCategoryEquipment: "ഉപകരണങ്ങൾ",
    expenseCategoryIrrigation: "ജലസേചനം",
    expenseCategoryTransport: "ഗതാഗതം",
    expenseCategoryLandRent: "നിലം വാടക",
    expenseCategoryOther: "മറ്റുള്ളവ",
    farmCalendar: "ഫാം കലണ്ടർ",
    farmCalendarTaskScheduler: "ഫാം കലണ്ടർ & ടാസ്ക് ഷെഡ്യൂളർ",
    scheduleManageTasks:
      "നിങ്ങളുടെ കൃഷി ടാസ്കുകൾ ഷെഡ്യൂൾ ചെയ്ത് കൈകാര്യം ചെയ്യുക",
    addTask: "ടാസ്ക് ചേർക്കുക",
    editTask: "ടാസ്ക് എഡിറ്റ് ചെയ്യുക",
    updateTask: "ടാസ്ക് അപ്ഡേറ്റ് ചെയ്യുക",
    taskTitle: "ടാസ്ക് ശീർഷകം",
    time: "സമയം",
    priority: "പ്രാധാന്യം",
    priorityLow: "കുറഞ്ഞ",
    priorityMedium: "ഇടത്തരം",
    priorityHigh: "ഉയർന്ന",
    status: "സ്ഥിതി",
    statusPending: "തീർച്ചപ്പെടുത്താത്ത",
    statusInProgress: "പുരോഗതിയിൽ",
    statusCompleted: "പൂർത്തിയാക്കി",
    taskCategoryPlanting: "നടൽ",
    taskCategoryHarvesting: "വിളവെടുപ്പ്",
    taskCategoryIrrigation: "ജലസേചനം",
    taskCategoryFertilizing: "എരുമ ഇടൽ",
    taskCategoryPestControl: "കീട നിയന്ത്രണം",
    taskCategoryPruning: "വെട്ടിമാറ്റൽ",
    taskCategoryWeeding: "കളനീക്കൽ",
    taskCategoryOther: "മറ്റുള്ളവ",
    tasksFor: "ടാസ്കുകൾ",
    noTasksForDate: "ഈ തീയതിക്ക് ടാസ്കുകളില്ല",
    upcomingTasks: "വരാനിരിക്കുന്ന ടാസ്കുകൾ",
    noUpcomingTasks: "വരാനിരിക്കുന്ന ടാസ്കുകളില്ല",
    filter: "ഫിൽറ്റർ",
    allCategories: "എല്ലാ വിഭാഗങ്ങളും",
    allStatuses: "എല്ലാ സ്ഥിതികളും",
    fillRequiredFields: "ദയവായി എല്ലാ ആവശ്യമായ ഫീൽഡുകളും പൂരിപ്പിക്കുക",
    confirmDeleteTask: "ഈ ടാസ്ക് ഡിലീറ്റ് ചെയ്യണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?",
    monthJanuary: "ജനുവരി",
    monthFebruary: "ഫെബ്രുവരി",
    monthMarch: "മാർച്ച്",
    monthApril: "ഏപ്രിൽ",
    monthMay: "മേയ്",
    monthJune: "ജൂൺ",
    monthJuly: "ജൂലൈ",
    monthAugust: "ഓഗസ്റ്റ്",
    monthSeptember: "സെപ്റ്റംബർ",
    monthOctober: "ഒക്ടോബർ",
    monthNovember: "നവംബർ",
    monthDecember: "ഡിസംബർ",
    daySunday: "ഞായർ",
    dayMonday: "തിങ്കൾ",
    dayTuesday: "ചൊവ്വ",
    dayWednesday: "ബുധൻ",
    dayThursday: "വ്യാഴം",
    dayFriday: "വെള്ളി",
    daySaturday: "ശനി",
    logout: "ലോഗ്‌ഔട്ട്",
    signInToYourAccount: "നിങ്ങളുടെ അക്കൗണ്ടിലേക്ക് പ്രവേശിക്കുക",
    signIn: "ലോഗിൻ",
    signingIn: "ലോഗിൻ ചെയ്യുന്നു...",
    dontHaveAccount: "അക്കൗണ്ട് ഇല്ലേയോ?",
    signUpHere: "ഇവിടെ രജിസ്റ്റർ ചെയ്യുക",
    createFarmerAccount: "കർഷക അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    creatingAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു...",
    alreadyHaveAccount: "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?",
    signInHere: "ഇവിടെ ലോഗിൻ ചെയ്യുക",
    welcomeBack: "വെൽക്കം തിരികെ,",
    farmingOverview: "ഇന്നത്തെ കൃഷി അവലോകനം",
    totalFarms: "ആകെ ഫാരങ്ങൾ",
    weather: "കാലാവസ്ഥ",
    activeCrops: "സജീവ വിളകൾ",
    loadingFarmData: "നിങ്ങളുടെ ഫാം ഡാറ്റ ലോഡ് ചെയ്യുന്നു...",
    pestControlCardTitle: "കീട നിയന്ത്രണം",
    pestControlCardSubtitle:
      "കീടങ്ങളെ തിരിച്ചറിയുകയും നിയന്ത്രിക്കുകയും ചെയ്യുക",
    marketPricesCardTitle: "മാർക്കറ്റ് വിലകൾ",
    marketPricesCardSubtitle: "നിലവിലെ നിരക്കുകൾ പരിശോധിക്കുക",
    weatherIn: "ഇവിടെയുള്ള കാലാവസ്ഥ:",
    humidity: "ആർദ്രത",
    rainfall: "മഴ",
    quickActions: "വേഗത്തിലുള്ള പ്രവർത്തനങ്ങൾ",
    manageFarms: "ഫാരങ്ങൾ കൈകാര്യം ചെയ്യുക",
    addNewFarm: "പുതിയ ഫാം ചേർക്കുക",
    yourFarms: "നിങ്ങളുടെ ഫാരങ്ങൾ",
    noFarmsYet: "ഇനിയും ഒരു ഫാമും ചേർത്തിട്ടില്ല",
    addFirstFarmText: "വിള നിർദേശങ്ങൾ ലഭിക്കാൻ ആദ്യ ഫാം ചേർക്കുക",
    addFirstFarmButton: "ആദ്യ ഫാം ചേർക്കുക",
    emailPlaceholder: "ഇമെയിൽ നൽകുക",
    passwordPlaceholder: "പാസ്‌വേഡ് നൽകുക",
    fullNamePlaceholder: "പൂർണ്ണ പേര്",
    emailAddressPlaceholder: "ഇമെയിൽ വിലാസം",
    phoneNumberPlaceholder: "ഫോൺ നമ്പർ",
    selectDistrictPlaceholder: "ജില്ല തിരഞ്ഞെടുക്കുക",
    villagePlaceholder: "ഗ്രാമം/ടൗൺ",
    createPasswordPlaceholder: "പാസ്‌വേഡ് സൃഷ്ടിക്കുക",
    languageEnglish: "ഇംഗ്ലീഷ്",
    languageMalayalam: "മലയാളം",
    languageTamil: "തമിഴ്",
    languageKannada: "കന്നഡ",
    languageTulu: "തുളു",
    languageKonkani: "കൊങ്കണി",
    languageHindi: "ഹിന്ദി",
    languageUrdu: "ഉർദു",
    languageLabelShort: "ഭാഷ",
    // Farms
    farmsTitle: "എന്റെ ഫാരങ്ങൾ",
    farmsSubtitle: "നിങ്ങളുടെ കൃഷിയിടങ്ങൾ നിയന്ത്രിക്കുക",
    addFarmButton: "ഫാം ചേർക്കുക",
    editFarmTitle: "ഫാം തിരുത്തുക",
    addNewFarmTitle: "പുതിയ ഫാം ചേർക്കുക",
    farmNameLabel: "ഫാമിന്റെ പേര്",
    farmNamePlaceholder: "ഫാമിന്റെ പേര് നൽകുക",
    locationLabel: "സ്ഥലം",
    locationPlaceholder: "ജില്ല, ഗ്രാമം",
    cropTypeLabel: "വിളയുടെ പേര്",
    cropTypePlaceholder: "വിള തിരഞ്ഞെടുക്കുക (ഐച്ചികം)",
    farmSizeLabel: "ഫാമിന്റെ വിസ്തീർണം",
    sizePlaceholder: "വലുപ്പം",
    acres: "ഏക്കർ",
    hectares: "ഹെക്ടർ",
    cancel: "റദ്ദാക്കുക",
    saving: "സംരക്ഷിക്കുന്നു...",
    saveFarm: "ഫാം സംരക്ഷിക്കുക",
    updateFarm: "അപ്ഡേറ്റ് ചെയ്യുക",
    addFarm: "ഫാം ചേർക്കുക",
    noFarmsAddedTitle: "ഇനിയും ഫാം ചേർത്തിട്ടില്ല",
    noFarmsAddedText: "കൃഷി നിർദേശങ്ങൾ ലഭിക്കാൻ ആദ്യ ഫാം ചേർക്കുക",
    addFirstFarmButtonFarms: "ആദ്യ ഫാം ചേർക്കുക",
    deleteFarmConfirm: "ഈ ഫാം ഡിലീറ്റ് ചെയ്യണോ?",
    // Crop Recommendations
    cropRecoTitle: "വിള നിർദേശങ്ങൾ",
    cropRecoSubtitle:
      "നിങ്ങളുടെ ഫാമിന്റെ സാഹചര്യങ്ങൾക്ക് അനുയോജ്യമായ AI അടിസ്ഥാനത്തിലുള്ള വിള നിർദേശങ്ങൾ",
    farmConditions: "ഫാം സാഹചര്യങ്ങൾ",
    soilTypeLabel: "മണ്ണിന്റെ തരം",
    waterAvailabilityLabel: "ജല ലഭ്യത",
    districtOptionalLabel: "ജില്ല (ഐച്ചികം)",
    districtPlaceholderReco: "ജില്ലയുടെ പേര് നൽകുക",
    analyzeButton: "വിള നിർദേശങ്ങൾ നേടുക",
    analyzingText: "ഫാം സാഹചര്യങ്ങൾ വിലയിരുത്തുന്നു...",
    analyzingSpinnerText: "നിങ്ങളുടെ ഫാം സാഹചര്യങ്ങൾ വിശകലനം ചെയ്യുന്നു...",
    noRecoTitle: "നിർദേശങ്ങൾ ഒന്നും കണ്ടെത്തിയില്ല",
    noRecoText: "മണ്ണ്, ജലം തുടങ്ങിയ വിവരം മാറ്റി വീണ്ടും ശ്രമിക്കുക",
    recommendedCropsTitle: "നിർദേശിച്ച വിളകൾ",
    seasonLabel: "സീസൺ",
    waterLabel: "വെള്ളം",
    durationLabel: "കാലാവധി",
    yieldLabel: "ഉടമ",
    benefitsLabel: "നേട്ടങ്ങൾ:",
    suitabilityHigh: "വളരെ അനുയോജ്യം",
    suitabilitySuitable: "അനുയോജ്യം",
    suitabilityModerate: "മദ്യസ്ഥമായി അനുയോജ്യം",
    suitabilityLow: "കുറച്ച് അനുയോജ്യം",
    // Market Prices
    marketTitle: "കേരള കൃഷി മാർക്കറ്റ് വിലകൾ",
    marketSubtitle:
      "കേരളത്തിലെ വിവിധ മാർക്കറ്റുകളിലെ തത്സമയ കൃഷി ഉൽപ്പന്ന വിലകൾ",
    commoditiesLabel: "ഉൽപ്പന്നങ്ങൾ",
    marketsLabel: "മാർക്കറ്റുകൾ",
    avgPriceLabel: "ശരാശരി വില",
    risingPricesLabel: "വില ഉയരുന്നു",
    filterPricesTitle: "വിലകൾ ഫിൽറ്റർ ചെയ്യുക",
    searchLabel: "ഉൽപ്പന്നങ്ങളും മാർക്കറ്റുകളും തിരയുക",
    searchPlaceholder: "അരി, തേങ്ങ, മാർക്കറ്റ് നാമങ്ങൾ എന്നിവ തിരയുക...",
    selectCommodityLabel: "ഉൽപ്പന്നം തിരഞ്ഞെടുക്കുക",
    allCommoditiesOption: "എല്ലാ ഉൽപ്പന്നങ്ങളും",
    selectDistrictLabel: "ജില്ല തിരഞ്ഞെടുക്കുക",
    refreshPricesButton: "വില പുതുക്കുക",
    refreshingButton: "പുതുക്കുന്നു...",
    exportCsvButton: "CSV ആയി എക്‌സ്‌പോർട്ട് ചെയ്യുക",
    clearFiltersButton: "ഫിൽറ്ററുകൾ നീക്കുക",
    marketTrendsTitle: "മാർക്കറ്റ് പ്രവണതകൾ",
    marketInsightTitle: "മാർക്കറ്റ് വിവരം:",
    marketInsightText:
      "സർക്കാർ APMC മാർക്കറ്റുകളിൽ നിന്നുള്ള വിലകൾ ദിവസം തോറും പുതുക്കുന്നു. മികച്ച വില ലഭിക്കാൻ നിരന്തരം പരിശോധിക്കുക.",
    sellingTipsTitle: "വിൽപ്പന നിർദേശങ്ങൾ",
    sellingTips1:
      "മറ്റുള്ളവുമായും താരതമ്യം ചെയ്ത് രാവിലെ വിൽക്കുന്നത് നല്ല വിലയ്ക്കുള്ള സാധ്യത വർധിപ്പിക്കും",
    sellingTips2: "വിവിധ മാർക്കറ്റുകളിലെ നിരക്കുകൾ പരിശോധിക്കുക",
    sellingTips3: "ഉൽപ്പന്നം ഗ്രേഡ് ചെയ്ത് ഉയർന്ന വില നേടുക",
    sellingTips4: "ആഴ്ച്ച്ചതോറും വില പ്രവണതകൾ നിരീക്ഷിക്കുക",
    sellingTips5: "സർക്കാർ വാങ്ങൽ സ്കീമുകൾ പരിഗണിക്കുക",
    marketPriceListTitle: "മാർക്കറ്റ് വില പട്ടിക",
    showingCommoditiesText: "പ്രദർശിപ്പിക്കുന്നത്",
    inText: "ജില്ലയിൽ",
    dateLabel: "തീയതി",
    loadingMarketTitle: "മാർക്കറ്റ് വില ലോഡ് ചെയ്യുന്നു",
    loadingMarketText:
      "കേരള മാർക്കറ്റുകളിൽ നിന്നുള്ള ഏറ്റവും പുതിയ വിലകൾ കൊണ്ടുവരുന്നു...",
    commodityColumn: "ഉൽപ്പന്നം",
    marketColumn: "മാർക്കറ്റ്",
    districtColumn: "ജില്ല",
    priceRangeColumn: "വില പരിധി",
    trendColumn: "പ്രവണത",
    updatedColumn: "അപ്ഡേറ്റ് ചെയ്തത്",
    perUnitText: "ഒരു",
    noMarketDataText:
      "നിങ്ങളുടെ ഫിൽറ്ററുകൾക്ക് അനുയോജ്യമായ മാർക്കറ്റ് ഡാറ്റ ലഭ്യമായില്ല. ഫിൽറ്ററുകൾ മാറ്റി വീണ്ടും ശ്രമിക്കുക.",
    tableFooterSource: "ഡേറ്റ: Agmarknet & കേരള കൃഷി വകുപ്പ്",
    tableFooterShowing: "പ്രദർശിപ്പിക്കുന്നത്",
    tableFooterOf: "മൊത്തം",
    tableFooterEntries: "എൻട്രികളിൽ നിന്നും",
    refreshButton: "റീഫ്രഷ് ചെയ്യുക",
    dataSourcesTitle: "ഡേറ്റാ സോഴ്സുകളും അപ്ഡേറ്റ്സും",
    agmarknetStatus: "Agmarknet API:",
    agmarknetConnected: "കണക്റ്റ് ചെയ്തിരിക്കുന്നു",
    agmarknetOffline: "ഓഫ്‌ലൈൻ",
    updatesEvery: "അപ്ഡേറ്റ്: ഓരോ 5 മിനിറ്റിലും",
    coverageLabel: "കവറേജ്:",
    nextUpdateText: "അടുത്ത അപ്ഡേറ്റ് 5 മിനിറ്റിന് ശേഷം",
    priceAlertsTitle: "വില അലർട്ടുകൾ",
    priceAlertsText:
      "നിങ്ങളുടെ വിളയ്ക്ക് ആവശ്യമായ വില എത്തിയാൽ അറിയിപ്പ് ലഭിക്കുക",
    setPriceAlertButton: "വില അലർട്ട് സജ്ജമാക്കുക",
    priceAlertPrompt: "വില അലർട്ട് സജ്ജമാക്കുക",
    priceAlertCurrent: "നിലവിലെ വില",
    priceAlertEnterTarget: "ലക്ഷ്യവില (₹ കിലോക്ക്): നൽകുക",
    priceAlertSuccess: "വില അലർട്ട് സജ്ജമായി!",
    nearestMarketsTitle: "അടുത്തുള്ള മാർക്കറ്റുകൾ",
    nearestMarketsText: "നിങ്ങളുടെ അടുത്തുള്ള കർഷക മാർക്കറ്റുകൾ കണ്ടെത്തുക",
    viewMapButton: "മാപ്പ് കാണുക",
    // Pest Management (Plant Health)
    plantIdOnline: "Plant.id v3 AI ഓൺലൈൻ",
    plantIdOffline: "അഡ്വാൻസ്ഡ് സിമുലേഷൻ ഉപയോഗിക്കുന്നു",
    plantIdChecking: "AI കണക്ഷൻ പരിശോധനയിൽ...",
    plantIdStatusOnline: "തത്സമയ രോഗ നിർണ്ണയം സജീവമാക്കി",
    plantIdStatusOffline: "ഇമേജ് അനലിസിസ് സിമുലേഷൻ ഉപയോഗിക്കുന്നു",
    plantIdStatusChecking: "Plant.id v3 API പരിശോധിക്കുന്നു...",
    aiScannerTitle: "AI പ്ലാന്റ് ഹെൽത്ത് സ്കാനർ",
    aiScannerSubtitle:
      "Plant.id v3 AI സാങ്കേതിക വിദ്യ ഉപയോഗിച്ച് കീട-രോഗ നിർണ്ണയം",
    uploadLeafTitle: "ഇലയുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    uploadLeafSubtitle:
      "ഉടൻ AI അടിസ്ഥാനത്തിലുള്ള രോഗ നിർണ്ണയംയും ചികിത്സ നിർദേശങ്ങളും",
    aiAnalysisInProgress: "AI വിശകലനം നടക്കുന്നു...",
    captureOrUpload: "ഇലയുടെ ചിത്രം പകർത്തുക അല്ലെങ്കിൽ അപ്‌ലോഡ് ചെയ്യുക",
    bestResultsText:
      "മികച്ച ഫലം ലഭിക്കാൻ: വെളിച്ചമുള്ള സ്ഥലത്ത് ചിത്രം എടുക്കുക, ബാധിത ഭാഗം വ്യക്തമാക്കുക, പല ഇലകളും ഉൾപ്പെടുത്തുക",
    selectImageButton: "ചിത്രം തിരഞ്ഞെടുക്കുക",
    analyzingWithAI: "AI ഉപയോഗിച്ച് വിശകലനം ചെയ്യുന്നു...",
    clearImageButton: "ചിത്രം മായ്ക്കുക",
    imagePreviewTitle: "ചിത്രം പ്രിവ്യൂ",
    readyForAI: "AI വിശകലനത്തിന് തയ്യാറാണ്",
    simulationTitle: "അഡ്വാൻസ്ഡ് സിമുലേഷൻ ഉപയോഗിക്കുന്നു",
    simulationMessage: "API കണക്ഷൻ പ്രശ്നം - ലോക്കൽ അനലിസിസ് ഉപയോഗിക്കുന്നു",
    technicalInfoTitle: "സാങ്കേതിക വിവരം:",
    technicalInfoOnline: "Plant.id v3 API ഉപയോഗിച്ച് യഥാർത്ഥ നിർണ്ണയം",
    technicalInfoOffline: "ഇമേജ് അനലിസിസ് ഉപയോഗിച്ച് അഡ്വാൻസ്ഡ് സിമുലേഷൻ",
    diseaseDetectedTitle: "രോഗം കണ്ടെത്തി",
    plantHealthyTitle: "ചെടി ആരോഗ്യമുണ്ട്",
    aiConfidenceLabel: "AI വിശ്വാസനിരക്ക്",
    diagnosisDetailsTitle: "നിർണ്ണയ വിശദാംശങ്ങൾ",
    scientificClassificationTitle: "ശാസ്ത്രീയ വർഗ്ഗീകരണം",
    treatmentTitle: "ചികിത്സ നിർദേശങ്ങൾ",
    treatmentFooter: "ആദ്യ ലക്ഷണങ്ങൾ കാണുമ്പോൾ തന്നെ ചികിത്സ ആരംഭിക്കുക",
    preventionTitle: "പ്രതിരോധ നടപടികൾ",
    careRecoTitle: "ചെടി പരിപാലന നിർദേശങ്ങൾ",
    analyzeAnotherImageButton: "മറ്റൊരു ചിത്രം വിശകലനം ചെയ്യുക",
    poweredByPlantIdTitle: "Plant.id v3 API ഉപയോഗിച്ച് പ്രവർത്തിക്കുന്നു",
    poweredByPlantIdText:
      "ലക്ഷക്കണക്കിന് സസ്യ ചിത്രങ്ങൾ ഉപയോഗിച്ച് പരിശീലിപ്പിച്ച മെഷീൻ ലേണിംഗ് മോഡലുകൾ",
    aiPoweredTitle: "AI അധിഷ്ഠിതം",
    aiPoweredText: "Plant.id v3 ന്യൂറൽ നെറ്റ്‌വർക്ക് ഉപയോഗിക്കുന്നു",
    globalDatabaseTitle: "ഗ്ലോബൽ ഡേറ്റാബേസ്",
    globalDatabaseText: "ആയിരക്കണക്കിന് സസ്യ ഇനങ്ങൾ",
    realtimeTitle: "തത്സമയ",
    realtimeText: "ഉടൻ വിശകലനവും ഫലവും",
    plantIdFooter: "സസ്യ രോഗ നിർണ്ണയത്തിന് Plant.id v3 API ഉപയോഗിക്കുന്നു",
    // Chatbot
    chatbotFloatingTooltip: "കർഷക അസിസ്റ്റന്റ്",
    chatbotHeaderTitle: "കർഷക അസിസ്റ്റന്റ്",
    chatbotHeaderSubtitle: "AI പ്രവർത്തിപ്പിക്കുന്നു",
    chatbotQuickQuestionsTitle: "വേഗത്തിലുള്ള ചോദ്യങ്ങൾ:",
    chatbotQuick1: "ഈ സീസണിൽ ഏറ്റവും നല്ല വിളകൾ?",
    chatbotQuick2: "നനയിടത്ത് കീട നിയന്ത്രണം?",
    chatbotQuick3: "ഓർഗാനിക് കൃഷി സ്കീമുകൾ",
    chatbotQuick4: "തേങ്ങ കൃഷി നിർദേശങ്ങൾ",
    chatbotQuick5: "കാലാവസ്ഥ നിർദേശങ്ങൾ",
    chatbotQuick6: "മാർക്കറ്റ് വിലകൾ",
    chatbotThinking: "ചിന്തിക്കുന്നു",
    chatbotPlaceholder: "കേരളത്തിലെ കൃഷിയെ കുറിച്ച് എന്തും ചോദിക്കൂ...",
    chatbotClear: "മാഷ് മായ്ക്കുക",
    chatbotPressEnter: "സന്ദേശം അയക്കാൻ Enter അമർത്തുക",
    chatbotError:
      "ക്ഷമിക്കണം, സാങ്കേതിക പ്രശ്നം അനുഭവപ്പെടുന്നു. ദയവായി പിന്നീട് ശ്രമിക്കുക.",
    chatbotGreeting:
      "നമസ്കാരം! 🙏 ഞാൻ നിങ്ങളുടെ കേരള കർഷക AI അസിസ്റ്റന്റാണ്, Google Gemini AI ഉപയോഗിച്ച് പ്രവർത്തിക്കുന്നു. കേരളത്തിലെ കർഷകർക്ക് ആവശ്യമായ കൃഷി വിവരം നൽകുക എന്നതാണ് എന്റെ പ്രധാന ലക്ഷ്യം.\n\nഇന്ന് കേരളത്തിലെ കൃഷിയെ കുറിച്ച് എന്താണ് നിങ്ങളറിയാൻ ആഗ്രഹിക്കുന്നത്?",
  },
  
};


export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("en");

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key) => translations[language][key] || key,
    }),
    [language]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};


export const useLanguage = () => useContext(LanguageContext);
