import React, { createContext, useContext, useState, useMemo } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    dashboard: 'Dashboard',
    myFarms: 'My Farms',
    cropAdvice: 'Crop Advice',
    pestControl: 'Pest Control',
    marketPrices: 'Market Prices',
    logout: 'Logout',
    signInToYourAccount: 'Sign in to your account',
    signIn: 'Sign In',
    signingIn: 'Signing In...',
    dontHaveAccount: "Don't have an account?",
    signUpHere: 'Sign up here',
    createFarmerAccount: 'Create your farmer account',
    createAccount: 'Create Account',
    creatingAccount: 'Creating Account...',
    alreadyHaveAccount: 'Already have an account?',
    signInHere: 'Sign in here',
    welcomeBack: 'Welcome back,',
    farmingOverview: "Here\'s your farming overview for today",
    totalFarms: 'Total Farms',
    weather: 'Weather',
    activeCrops: 'Active Crops',
    loadingFarmData: 'Loading your farm data...',
    pestControlCardTitle: 'Pest Control',
    pestControlCardSubtitle: 'Identify & manage pests',
    marketPricesCardTitle: 'Market Prices',
    marketPricesCardSubtitle: 'Check current rates',
    weatherIn: 'Weather in',
    humidity: 'Humidity',
    rainfall: 'Rainfall',
    quickActions: 'Quick Actions',
    manageFarms: 'Manage Farms',
    addNewFarm: 'Add New Farm',
    yourFarms: 'Your Farms',
    noFarmsYet: 'No farms yet',
    addFirstFarmText: 'Add your first farm to get started with crop recommendations',
    addFirstFarmButton: 'Add Your First Farm',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    fullNamePlaceholder: 'Full Name',
    emailAddressPlaceholder: 'Email Address',
    phoneNumberPlaceholder: 'Phone Number',
    selectDistrictPlaceholder: 'Select District',
    villagePlaceholder: 'Village/Town',
    createPasswordPlaceholder: 'Create Password',
    languageEnglish: 'English',
    languageMalayalam: 'Malayalam',
    languageTamil: 'Tamil',
    languageKannada: 'Kannada',
    languageTulu: 'Tulu',
    languageKonkani: 'Konkani',
    languageHindi: 'Hindi',
    languageUrdu: 'Urdu',
    languageLabelShort: 'Language',
    // Farms
    farmsTitle: 'My Farms',
    farmsSubtitle: 'Manage your agricultural lands',
    addFarmButton: 'Add Farm',
    editFarmTitle: 'Edit Farm',
    addNewFarmTitle: 'Add New Farm',
    farmNameLabel: 'Farm Name',
    farmNamePlaceholder: 'Enter farm name',
    locationLabel: 'Location',
    locationPlaceholder: 'District, Village',
    cropTypeLabel: 'Crop Type',
    cropTypePlaceholder: 'Select Crop (Optional)',
    farmSizeLabel: 'Farm Size',
    sizePlaceholder: 'Size',
    acres: 'Acres',
    hectares: 'Hectares',
    cancel: 'Cancel',
    saving: 'Saving...',
    saveFarm: 'Save Farm',
    updateFarm: 'Update Farm',
    addFarm: 'Add Farm',
    noFarmsAddedTitle: 'No farms added yet',
    noFarmsAddedText: 'Add your first farm to start getting agricultural advice',
    addFirstFarmButtonFarms: 'Add Your First Farm',
    deleteFarmConfirm: 'Are you sure you want to delete this farm?',
    // Crop Recommendations
    cropRecoTitle: 'Crop Recommendations',
    cropRecoSubtitle: 'Get AI-powered crop suggestions based on your farm conditions',
    farmConditions: 'Farm Conditions',
    soilTypeLabel: 'Soil Type',
    waterAvailabilityLabel: 'Water Availability',
    districtOptionalLabel: 'District (Optional)',
    districtPlaceholderReco: 'Enter your district',
    analyzeButton: 'Get Crop Recommendations',
    analyzingText: 'Analyzing Farm Conditions...',
    analyzingSpinnerText: 'Analyzing your farm conditions...',
    noRecoTitle: 'No recommendations found',
    noRecoText: 'Try adjusting your farm conditions for better results',
    recommendedCropsTitle: 'Recommended Crops',
    seasonLabel: 'Season',
    waterLabel: 'Water',
    durationLabel: 'Duration',
    yieldLabel: 'Yield',
    benefitsLabel: 'Benefits:',
    suitabilityHigh: 'Highly Suitable',
    suitabilitySuitable: 'Suitable',
    suitabilityModerate: 'Moderately Suitable',
    suitabilityLow: 'Less Suitable',
    // Market Prices
    marketTitle: 'Kerala Agricultural Market Prices',
    marketSubtitle: 'Real-time commodity prices across Kerala markets',
    commoditiesLabel: 'Commodities',
    marketsLabel: 'Markets',
    avgPriceLabel: 'Avg Price',
    risingPricesLabel: 'Rising Prices',
    filterPricesTitle: 'Filter Prices',
    searchLabel: 'Search Commodities & Markets',
    searchPlaceholder: 'Search rice, coconut, market names...',
    selectCommodityLabel: 'Select Commodity',
    allCommoditiesOption: 'All Commodities',
    selectDistrictLabel: 'Select District',
    refreshPricesButton: 'Refresh Prices',
    refreshingButton: 'Refreshing...',
    exportCsvButton: 'Export as CSV',
    clearFiltersButton: 'Clear Filters',
    marketTrendsTitle: 'Market Trends',
    marketInsightTitle: 'Market Insight:',
    marketInsightText: 'Prices update daily from government APMC markets. Check regularly for best selling times.',
    sellingTipsTitle: 'Selling Tips',
    sellingTips1: 'Sell in morning hours for better prices',
    sellingTips2: 'Check multiple market rates',
    sellingTips3: 'Grade your produce for premium pricing',
    sellingTips4: 'Monitor weekly price trends',
    sellingTips5: 'Consider government procurement schemes',
    marketPriceListTitle: 'Market Price List',
    showingCommoditiesText: 'Showing',
    inText: 'in',
    dateLabel: 'Date',
    loadingMarketTitle: 'Loading Market Prices',
    loadingMarketText: 'Fetching latest prices from Kerala markets...',
    commodityColumn: 'Commodity',
    marketColumn: 'Market',
    districtColumn: 'District',
    priceRangeColumn: 'Price Range',
    trendColumn: 'Trend',
    updatedColumn: 'Updated',
    perUnitText: 'per',
    noMarketDataText: 'No market data found for your filters. Try different selection.',
    tableFooterSource: 'Data sourced from Agmarknet & Kerala Agricultural Department',
    tableFooterShowing: 'Showing',
    tableFooterOf: 'of',
    tableFooterEntries: 'entries',
    refreshButton: 'Refresh',
    dataSourcesTitle: 'Data Sources & Updates',
    agmarknetStatus: 'Agmarknet API:',
    agmarknetConnected: 'Connected',
    agmarknetOffline: 'Offline',
    updatesEvery: 'Updates: Every 5 minutes',
    coverageLabel: 'Coverage:',
    nextUpdateText: 'Next update in 5 minutes',
    priceAlertsTitle: 'Price Alerts',
    priceAlertsText: 'Get notified when your crop prices reach target levels',
    setPriceAlertButton: 'Set Price Alert',
    priceAlertPrompt: 'Set price alert for',
    priceAlertCurrent: 'Current price',
    priceAlertEnterTarget: 'Enter target price (₹ per kg):',
    priceAlertSuccess: 'Price alert set!',
    nearestMarketsTitle: 'Nearest Markets',
    nearestMarketsText: 'Find Agricultural Produce Market Committees near you',
    viewMapButton: 'View Map',
    // Pest Management (Plant Health)
    plantIdOnline: 'Plant.id v3 AI Online',
    plantIdOffline: 'Using Advanced Simulation',
    plantIdChecking: 'Testing AI Connection...',
    plantIdStatusOnline: 'Real-time disease detection active',
    plantIdStatusOffline: 'Advanced image analysis simulation',
    plantIdStatusChecking: 'Checking Plant.id v3 API...',
    aiScannerTitle: 'AI Plant Health Scanner',
    aiScannerSubtitle: 'Advanced pest and disease detection using Plant.id v3 AI technology',
    uploadLeafTitle: 'Upload Plant Leaf Image',
    uploadLeafSubtitle: 'Get instant AI-powered diagnosis and treatment recommendations',
    aiAnalysisInProgress: 'AI Analysis in Progress...',
    captureOrUpload: 'Capture or Upload Leaf Image',
    bestResultsText: 'For best results: Take clear photo in daylight, focus on affected areas, include multiple leaves if possible',
    selectImageButton: 'Select Image',
    analyzingWithAI: 'Analyzing with AI...',
    clearImageButton: 'Clear Image',
    imagePreviewTitle: 'Image Preview',
    readyForAI: 'Ready for AI Analysis',
    simulationTitle: 'Using Advanced Simulation',
    simulationMessage: 'API connection issue - using local analysis',
    technicalInfoTitle: 'Technical Info:',
    technicalInfoOnline: 'Using Plant.id v3 API for real detection',
    technicalInfoOffline: 'Using advanced simulation with image analysis',
    diseaseDetectedTitle: 'Disease Detected',
    plantHealthyTitle: 'Plant is Healthy',
    aiConfidenceLabel: 'AI Confidence',
    diagnosisDetailsTitle: 'Diagnosis Details',
    scientificClassificationTitle: 'Scientific Classification',
    treatmentTitle: 'Recommended Treatment',
    treatmentFooter: 'Apply treatment at first signs',
    preventionTitle: 'Prevention Measures',
    careRecoTitle: 'Plant Care Recommendations',
    analyzeAnotherImageButton: 'Analyze Another Image',
    poweredByPlantIdTitle: 'Powered by Plant.id v3 API',
    poweredByPlantIdText: 'Advanced machine learning trained on millions of plant images for accurate disease detection',
    aiPoweredTitle: 'AI-Powered',
    aiPoweredText: 'Uses Plant.id v3 neural networks',
    globalDatabaseTitle: 'Global Database',
    globalDatabaseText: 'Thousands of plant species',
    realtimeTitle: 'Real-time',
    realtimeText: 'Instant analysis and results',
    plantIdFooter: 'Using Plant.id v3 API for plant disease detection',
    // Chatbot
    chatbotFloatingTooltip: 'Farmers Assistant',
    chatbotHeaderTitle: 'Farmers Assistant',
    chatbotHeaderSubtitle: 'Powered by AI',
    chatbotQuickQuestionsTitle: 'Quick Questions:',
    chatbotQuick1: 'Best crops for this season?',
    chatbotQuick2: 'Pest control in paddy fields?',
    chatbotQuick3: 'Organic farming schemes',
    chatbotQuick4: 'Coconut farming tips',
    chatbotQuick5: 'Weather advice',
    chatbotQuick6: 'Market prices',
    chatbotThinking: 'Thinking',
    chatbotPlaceholder: 'Ask about farming in Kerala...',
    chatbotClear: 'Clear',
    chatbotPressEnter: 'Press Enter to send',
    chatbotError: "I apologize, but I'm experiencing technical difficulties. Please try again later.",
    chatbotGreeting:
      "Namaskaram! 🙏 I'm your dedicated Kerala Farmers AI Assistant, powered by Google Gemini AI. I specialize in providing accurate agricultural information for Kerala farmers.\n\nWhat would you like to know about farming in Kerala today?",
  },
  ml: {
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    myFarms: 'എന്റെ ഫാരങ്ങൾ',
    cropAdvice: 'വിള നിർദേശങ്ങൾ',
    pestControl: 'കീട നിയന്ത്രണം',
    marketPrices: 'മാർക്കറ്റ് വിലകൾ',
    logout: 'ലോഗ്‌ഔട്ട്',
    signInToYourAccount: 'നിങ്ങളുടെ അക്കൗണ്ടിലേക്ക് പ്രവേശിക്കുക',
    signIn: 'ലോഗിൻ',
    signingIn: 'ലോഗിൻ ചെയ്യുന്നു...',
    dontHaveAccount: 'അക്കൗണ്ട് ഇല്ലേയോ?',
    signUpHere: 'ഇവിടെ രജിസ്റ്റർ ചെയ്യുക',
    createFarmerAccount: 'കർഷക അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    createAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    creatingAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു...',
    alreadyHaveAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    signInHere: 'ഇവിടെ ലോഗിൻ ചെയ്യുക',
    welcomeBack: 'വെൽക്കം തിരികെ,',
    farmingOverview: 'ഇന്നത്തെ കൃഷി അവലോകനം',
    totalFarms: 'ആകെ ഫാരങ്ങൾ',
    weather: 'കാലാവസ്ഥ',
    activeCrops: 'സജീവ വിളകൾ',
    loadingFarmData: 'നിങ്ങളുടെ ഫാം ഡാറ്റ ലോഡ് ചെയ്യുന്നു...',
    pestControlCardTitle: 'കീട നിയന്ത്രണം',
    pestControlCardSubtitle: 'കീടങ്ങളെ തിരിച്ചറിയുകയും നിയന്ത്രിക്കുകയും ചെയ്യുക',
    marketPricesCardTitle: 'മാർക്കറ്റ് വിലകൾ',
    marketPricesCardSubtitle: 'നിലവിലെ നിരക്കുകൾ പരിശോധിക്കുക',
    weatherIn: 'ഇവിടെയുള്ള കാലാവസ്ഥ:',
    humidity: 'ആർദ്രത',
    rainfall: 'മഴ',
    quickActions: 'വേഗത്തിലുള്ള പ്രവർത്തനങ്ങൾ',
    manageFarms: 'ഫാരങ്ങൾ കൈകാര്യം ചെയ്യുക',
    addNewFarm: 'പുതിയ ഫാം ചേർക്കുക',
    yourFarms: 'നിങ്ങളുടെ ഫാരങ്ങൾ',
    noFarmsYet: 'ഇനിയും ഒരു ഫാമും ചേർത്തിട്ടില്ല',
    addFirstFarmText: 'വിള നിർദേശങ്ങൾ ലഭിക്കാൻ ആദ്യ ഫാം ചേർക്കുക',
    addFirstFarmButton: 'ആദ്യ ഫാം ചേർക്കുക',
    emailPlaceholder: 'ഇമെയിൽ നൽകുക',
    passwordPlaceholder: 'പാസ്‌വേഡ് നൽകുക',
    fullNamePlaceholder: 'പൂർണ്ണ പേര്',
    emailAddressPlaceholder: 'ഇമെയിൽ വിലാസം',
    phoneNumberPlaceholder: 'ഫോൺ നമ്പർ',
    selectDistrictPlaceholder: 'ജില്ല തിരഞ്ഞെടുക്കുക',
    villagePlaceholder: 'ഗ്രാമം/ടൗൺ',
    createPasswordPlaceholder: 'പാസ്‌വേഡ് സൃഷ്ടിക്കുക',
    languageEnglish: 'ഇംഗ്ലീഷ്',
    languageMalayalam: 'മലയാളം',
    languageTamil: 'തമിഴ്',
    languageKannada: 'കന്നഡ',
    languageTulu: 'തുളു',
    languageKonkani: 'കൊങ്കണി',
    languageHindi: 'ഹിന്ദി',
    languageUrdu: 'ഉർദു',
    languageLabelShort: 'ഭാഷ',
    // Farms
    farmsTitle: 'എന്റെ ഫാരങ്ങൾ',
    farmsSubtitle: 'നിങ്ങളുടെ കൃഷിയിടങ്ങൾ നിയന്ത്രിക്കുക',
    addFarmButton: 'ഫാം ചേർക്കുക',
    editFarmTitle: 'ഫാം തിരുത്തുക',
    addNewFarmTitle: 'പുതിയ ഫാം ചേർക്കുക',
    farmNameLabel: 'ഫാമിന്റെ പേര്',
    farmNamePlaceholder: 'ഫാമിന്റെ പേര് നൽകുക',
    locationLabel: 'സ്ഥലം',
    locationPlaceholder: 'ജില്ല, ഗ്രാമം',
    cropTypeLabel: 'വിളയുടെ പേര്',
    cropTypePlaceholder: 'വിള തിരഞ്ഞെടുക്കുക (ഐച്ചികം)',
    farmSizeLabel: 'ഫാമിന്റെ വിസ്തീർണം',
    sizePlaceholder: 'വലുപ്പം',
    acres: 'ഏക്കർ',
    hectares: 'ഹെക്ടർ',
    cancel: 'റദ്ദാക്കുക',
    saving: 'സംരക്ഷിക്കുന്നു...',
    saveFarm: 'ഫാം സംരക്ഷിക്കുക',
    updateFarm: 'അപ്ഡേറ്റ് ചെയ്യുക',
    addFarm: 'ഫാം ചേർക്കുക',
    noFarmsAddedTitle: 'ഇനിയും ഫാം ചേർത്തിട്ടില്ല',
    noFarmsAddedText: 'കൃഷി നിർദേശങ്ങൾ ലഭിക്കാൻ ആദ്യ ഫാം ചേർക്കുക',
    addFirstFarmButtonFarms: 'ആദ്യ ഫാം ചേർക്കുക',
    deleteFarmConfirm: 'ഈ ഫാം ഡിലീറ്റ് ചെയ്യണോ?',
    // Crop Recommendations
    cropRecoTitle: 'വിള നിർദേശങ്ങൾ',
    cropRecoSubtitle: 'നിങ്ങളുടെ ഫാമിന്റെ സാഹചര്യങ്ങൾക്ക് അനുയോജ്യമായ AI അടിസ്ഥാനത്തിലുള്ള വിള നിർദേശങ്ങൾ',
    farmConditions: 'ഫാം സാഹചര്യങ്ങൾ',
    soilTypeLabel: 'മണ്ണിന്റെ തരം',
    waterAvailabilityLabel: 'ജല ലഭ്യത',
    districtOptionalLabel: 'ജില്ല (ഐച്ചികം)',
    districtPlaceholderReco: 'ജില്ലയുടെ പേര് നൽകുക',
    analyzeButton: 'വിള നിർദേശങ്ങൾ നേടുക',
    analyzingText: 'ഫാം സാഹചര്യങ്ങൾ വിലയിരുത്തുന്നു...',
    analyzingSpinnerText: 'നിങ്ങളുടെ ഫാം സാഹചര്യങ്ങൾ വിശകലനം ചെയ്യുന്നു...',
    noRecoTitle: 'നിർദേശങ്ങൾ ഒന്നും കണ്ടെത്തിയില്ല',
    noRecoText: 'മണ്ണ്, ജലം തുടങ്ങിയ വിവരം മാറ്റി വീണ്ടും ശ്രമിക്കുക',
    recommendedCropsTitle: 'നിർദേശിച്ച വിളകൾ',
    seasonLabel: 'സീസൺ',
    waterLabel: 'വെള്ളം',
    durationLabel: 'കാലാവധി',
    yieldLabel: 'ഉടമ',
    benefitsLabel: 'നേട്ടങ്ങൾ:',
    suitabilityHigh: 'വളരെ അനുയോജ്യം',
    suitabilitySuitable: 'അനുയോജ്യം',
    suitabilityModerate: 'മദ്യസ്ഥമായി അനുയോജ്യം',
    suitabilityLow: 'കുറച്ച് അനുയോജ്യം',
    // Market Prices
    marketTitle: 'കേരള കൃഷി മാർക്കറ്റ് വിലകൾ',
    marketSubtitle: 'കേരളത്തിലെ വിവിധ മാർക്കറ്റുകളിലെ തത്സമയ കൃഷി ഉൽപ്പന്ന വിലകൾ',
    commoditiesLabel: 'ഉൽപ്പന്നങ്ങൾ',
    marketsLabel: 'മാർക്കറ്റുകൾ',
    avgPriceLabel: 'ശരാശരി വില',
    risingPricesLabel: 'വില ഉയരുന്നു',
    filterPricesTitle: 'വിലകൾ ഫിൽറ്റർ ചെയ്യുക',
    searchLabel: 'ഉൽപ്പന്നങ്ങളും മാർക്കറ്റുകളും തിരയുക',
    searchPlaceholder: 'അരി, തേങ്ങ, മാർക്കറ്റ് നാമങ്ങൾ എന്നിവ തിരയുക...',
    selectCommodityLabel: 'ഉൽപ്പന്നം തിരഞ്ഞെടുക്കുക',
    allCommoditiesOption: 'എല്ലാ ഉൽപ്പന്നങ്ങളും',
    selectDistrictLabel: 'ജില്ല തിരഞ്ഞെടുക്കുക',
    refreshPricesButton: 'വില പുതുക്കുക',
    refreshingButton: 'പുതുക്കുന്നു...',
    exportCsvButton: 'CSV ആയി എക്‌സ്‌പോർട്ട് ചെയ്യുക',
    clearFiltersButton: 'ഫിൽറ്ററുകൾ നീക്കുക',
    marketTrendsTitle: 'മാർക്കറ്റ് പ്രവണതകൾ',
    marketInsightTitle: 'മാർക്കറ്റ് വിവരം:',
    marketInsightText: 'സർക്കാർ APMC മാർക്കറ്റുകളിൽ നിന്നുള്ള വിലകൾ ദിവസം തോറും പുതുക്കുന്നു. മികച്ച വില ലഭിക്കാൻ നിരന്തരം പരിശോധിക്കുക.',
    sellingTipsTitle: 'വിൽപ്പന നിർദേശങ്ങൾ',
    sellingTips1: 'മറ്റുള്ളവുമായും താരതമ്യം ചെയ്ത് രാവിലെ വിൽക്കുന്നത് നല്ല വിലയ്ക്കുള്ള സാധ്യത വർധിപ്പിക്കും',
    sellingTips2: 'വിവിധ മാർക്കറ്റുകളിലെ നിരക്കുകൾ പരിശോധിക്കുക',
    sellingTips3: 'ഉൽപ്പന്നം ഗ്രേഡ് ചെയ്ത് ഉയർന്ന വില നേടുക',
    sellingTips4: 'ആഴ്ച്ച്ചതോറും വില പ്രവണതകൾ നിരീക്ഷിക്കുക',
    sellingTips5: 'സർക്കാർ വാങ്ങൽ സ്കീമുകൾ പരിഗണിക്കുക',
    marketPriceListTitle: 'മാർക്കറ്റ് വില പട്ടിക',
    showingCommoditiesText: 'പ്രദർശിപ്പിക്കുന്നത്',
    inText: 'ജില്ലയിൽ',
    dateLabel: 'തീയതി',
    loadingMarketTitle: 'മാർക്കറ്റ് വില ലോഡ് ചെയ്യുന്നു',
    loadingMarketText: 'കേരള മാർക്കറ്റുകളിൽ നിന്നുള്ള ഏറ്റവും പുതിയ വിലകൾ കൊണ്ടുവരുന്നു...',
    commodityColumn: 'ഉൽപ്പന്നം',
    marketColumn: 'മാർക്കറ്റ്',
    districtColumn: 'ജില്ല',
    priceRangeColumn: 'വില പരിധി',
    trendColumn: 'പ്രവണത',
    updatedColumn: 'അപ്ഡേറ്റ് ചെയ്തത്',
    perUnitText: 'ഒരു',
    noMarketDataText: 'നിങ്ങളുടെ ഫിൽറ്ററുകൾക്ക് അനുയോജ്യമായ മാർക്കറ്റ് ഡാറ്റ ലഭ്യമായില്ല. ഫിൽറ്ററുകൾ മാറ്റി വീണ്ടും ശ്രമിക്കുക.',
    tableFooterSource: 'ഡേറ്റ: Agmarknet & കേരള കൃഷി വകുപ്പ്',
    tableFooterShowing: 'പ്രദർശിപ്പിക്കുന്നത്',
    tableFooterOf: 'മൊത്തം',
    tableFooterEntries: 'എൻട്രികളിൽ നിന്നും',
    refreshButton: 'റീഫ്രഷ് ചെയ്യുക',
    dataSourcesTitle: 'ഡേറ്റാ സോഴ്സുകളും അപ്ഡേറ്റ്സും',
    agmarknetStatus: 'Agmarknet API:',
    agmarknetConnected: 'കണക്റ്റ് ചെയ്തിരിക്കുന്നു',
    agmarknetOffline: 'ഓഫ്‌ലൈൻ',
    updatesEvery: 'അപ്ഡേറ്റ്: ഓരോ 5 മിനിറ്റിലും',
    coverageLabel: 'കവറേജ്:',
    nextUpdateText: 'അടുത്ത അപ്ഡേറ്റ് 5 മിനിറ്റിന് ശേഷം',
    priceAlertsTitle: 'വില അലർട്ടുകൾ',
    priceAlertsText: 'നിങ്ങളുടെ വിളയ്ക്ക് ആവശ്യമായ വില എത്തിയാൽ അറിയിപ്പ് ലഭിക്കുക',
    setPriceAlertButton: 'വില അലർട്ട് സജ്ജമാക്കുക',
    priceAlertPrompt: 'വില അലർട്ട് സജ്ജമാക്കുക',
    priceAlertCurrent: 'നിലവിലെ വില',
    priceAlertEnterTarget: 'ലക്ഷ്യവില (₹ കിലോക്ക്): നൽകുക',
    priceAlertSuccess: 'വില അലർട്ട് സജ്ജമായി!',
    nearestMarketsTitle: 'അടുത്തുള്ള മാർക്കറ്റുകൾ',
    nearestMarketsText: 'നിങ്ങളുടെ അടുത്തുള്ള കർഷക മാർക്കറ്റുകൾ കണ്ടെത്തുക',
    viewMapButton: 'മാപ്പ് കാണുക',
    // Pest Management (Plant Health)
    plantIdOnline: 'Plant.id v3 AI ഓൺലൈൻ',
    plantIdOffline: 'അഡ്വാൻസ്ഡ് സിമുലേഷൻ ഉപയോഗിക്കുന്നു',
    plantIdChecking: 'AI കണക്ഷൻ പരിശോധനയിൽ...',
    plantIdStatusOnline: 'തത്സമയ രോഗ നിർണ്ണയം സജീവമാക്കി',
    plantIdStatusOffline: 'ഇമേജ് അനലിസിസ് സിമുലേഷൻ ഉപയോഗിക്കുന്നു',
    plantIdStatusChecking: 'Plant.id v3 API പരിശോധിക്കുന്നു...',
    aiScannerTitle: 'AI പ്ലാന്റ് ഹെൽത്ത് സ്കാനർ',
    aiScannerSubtitle: 'Plant.id v3 AI സാങ്കേതിക വിദ്യ ഉപയോഗിച്ച് കീട-രോഗ നിർണ്ണയം',
    uploadLeafTitle: 'ഇലയുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    uploadLeafSubtitle: 'ഉടൻ AI അടിസ്ഥാനത്തിലുള്ള രോഗ നിർണ്ണയംയും ചികിത്സ നിർദേശങ്ങളും',
    aiAnalysisInProgress: 'AI വിശകലനം നടക്കുന്നു...',
    captureOrUpload: 'ഇലയുടെ ചിത്രം പകർത്തുക അല്ലെങ്കിൽ അപ്‌ലോഡ് ചെയ്യുക',
    bestResultsText: 'മികച്ച ഫലം ലഭിക്കാൻ: വെളിച്ചമുള്ള സ്ഥലത്ത് ചിത്രം എടുക്കുക, ബാധിത ഭാഗം വ്യക്തമാക്കുക, പല ഇലകളും ഉൾപ്പെടുത്തുക',
    selectImageButton: 'ചിത്രം തിരഞ്ഞെടുക്കുക',
    analyzingWithAI: 'AI ഉപയോഗിച്ച് വിശകലനം ചെയ്യുന്നു...',
    clearImageButton: 'ചിത്രം മായ്ക്കുക',
    imagePreviewTitle: 'ചിത്രം പ്രിവ്യൂ',
    readyForAI: 'AI വിശകലനത്തിന് തയ്യാറാണ്',
    simulationTitle: 'അഡ്വാൻസ്ഡ് സിമുലേഷൻ ഉപയോഗിക്കുന്നു',
    simulationMessage: 'API കണക്ഷൻ പ്രശ്നം - ലോക്കൽ അനലിസിസ് ഉപയോഗിക്കുന്നു',
    technicalInfoTitle: 'സാങ്കേതിക വിവരം:',
    technicalInfoOnline: 'Plant.id v3 API ഉപയോഗിച്ച് യഥാർത്ഥ നിർണ്ണയം',
    technicalInfoOffline: 'ഇമേജ് അനലിസിസ് ഉപയോഗിച്ച് അഡ്വാൻസ്ഡ് സിമുലേഷൻ',
    diseaseDetectedTitle: 'രോഗം കണ്ടെത്തി',
    plantHealthyTitle: 'ചെടി ആരോഗ്യമുണ്ട്',
    aiConfidenceLabel: 'AI വിശ്വാസനിരക്ക്',
    diagnosisDetailsTitle: 'നിർണ്ണയ വിശദാംശങ്ങൾ',
    scientificClassificationTitle: 'ശാസ്ത്രീയ വർഗ്ഗീകരണം',
    treatmentTitle: 'ചികിത്സ നിർദേശങ്ങൾ',
    treatmentFooter: 'ആദ്യ ലക്ഷണങ്ങൾ കാണുമ്പോൾ തന്നെ ചികിത്സ ആരംഭിക്കുക',
    preventionTitle: 'പ്രതിരോധ നടപടികൾ',
    careRecoTitle: 'ചെടി പരിപാലന നിർദേശങ്ങൾ',
    analyzeAnotherImageButton: 'മറ്റൊരു ചിത്രം വിശകലനം ചെയ്യുക',
    poweredByPlantIdTitle: 'Plant.id v3 API ഉപയോഗിച്ച് പ്രവർത്തിക്കുന്നു',
    poweredByPlantIdText: 'ലക്ഷക്കണക്കിന് സസ്യ ചിത്രങ്ങൾ ഉപയോഗിച്ച് പരിശീലിപ്പിച്ച മെഷീൻ ലേണിംഗ് മോഡലുകൾ',
    aiPoweredTitle: 'AI അധിഷ്ഠിതം',
    aiPoweredText: 'Plant.id v3 ന്യൂറൽ നെറ്റ്‌വർക്ക് ഉപയോഗിക്കുന്നു',
    globalDatabaseTitle: 'ഗ്ലോബൽ ഡേറ്റാബേസ്',
    globalDatabaseText: 'ആയിരക്കണക്കിന് സസ്യ ഇനങ്ങൾ',
    realtimeTitle: 'തത്സമയ',
    realtimeText: 'ഉടൻ വിശകലനവും ഫലവും',
    plantIdFooter: 'സസ്യ രോഗ നിർണ്ണയത്തിന് Plant.id v3 API ഉപയോഗിക്കുന്നു',
    // Chatbot
    chatbotFloatingTooltip: 'കർഷക അസിസ്റ്റന്റ്',
    chatbotHeaderTitle: 'കർഷക അസിസ്റ്റന്റ്',
    chatbotHeaderSubtitle: 'AI പ്രവർത്തിപ്പിക്കുന്നു',
    chatbotQuickQuestionsTitle: 'വേഗത്തിലുള്ള ചോദ്യങ്ങൾ:',
    chatbotQuick1: 'ഈ സീസണിൽ ഏറ്റവും നല്ല വിളകൾ?',
    chatbotQuick2: 'നനയിടത്ത് കീട നിയന്ത്രണം?',
    chatbotQuick3: 'ഓർഗാനിക് കൃഷി സ്കീമുകൾ',
    chatbotQuick4: 'തേങ്ങ കൃഷി നിർദേശങ്ങൾ',
    chatbotQuick5: 'കാലാവസ്ഥ നിർദേശങ്ങൾ',
    chatbotQuick6: 'മാർക്കറ്റ് വിലകൾ',
    chatbotThinking: 'ചിന്തിക്കുന്നു',
    chatbotPlaceholder: 'കേരളത്തിലെ കൃഷിയെ കുറിച്ച് എന്തും ചോദിക്കൂ...',
    chatbotClear: 'മാഷ് മായ്ക്കുക',
    chatbotPressEnter: 'സന്ദേശം അയക്കാൻ Enter അമർത്തുക',
    chatbotError: 'ക്ഷമിക്കണം, സാങ്കേതിക പ്രശ്നം അനുഭവപ്പെടുന്നു. ദയവായി പിന്നീട് ശ്രമിക്കുക.',
    chatbotGreeting:
      "നമസ്കാരം! 🙏 ഞാൻ നിങ്ങളുടെ കേരള കർഷക AI അസിസ്റ്റന്റാണ്, Google Gemini AI ഉപയോഗിച്ച് പ്രവർത്തിക്കുന്നു. കേരളത്തിലെ കർഷകർക്ക് ആവശ്യമായ കൃഷി വിവരം നൽകുക എന്നതാണ് എന്റെ പ്രധാന ലക്ഷ്യം.\n\nഇന്ന് കേരളത്തിലെ കൃഷിയെ കുറിച്ച് എന്താണ് നിങ്ങളറിയാൻ ആഗ്രഹിക്കുന്നത്?",
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    myFarms: 'என் பண்ணைகள்',
    cropAdvice: 'விளைச்சல் ஆலோசனை',
    pestControl: 'பூச்சி கட்டுப்பாடு',
    marketPrices: 'சந்தை விலைகள்',
    logout: 'வெளியேறு',
    signInToYourAccount: 'உங்கள் கணக்கில் உள்நுழைக',
    signIn: 'உள்நுழை',
    signingIn: 'உள்நுழைகிறது...',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    signUpHere: 'இங்கே பதிவு செய்யவும்',
    createFarmerAccount: 'உங்கள் விவசாயி கணக்கை உருவாக்கவும்',
    createAccount: 'கணக்கு உருவாக்கவும்',
    creatingAccount: 'கணக்கு உருவாக்கப்படுகிறது...',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    signInHere: 'இங்கே உள்நுழைக',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்,',
    farmingOverview: 'இன்றைய உங்கள் விவசாய நிலை கண்ணோட்டம்',
    totalFarms: 'மொத்த பண்ணைகள்',
    weather: 'வானிலை',
    activeCrops: 'செயலில் உள்ள பயிர்கள்',
    loadingFarmData: 'உங்கள் பண்ணை தரவு ஏற்றப்படுகிறது...',
    pestControlCardTitle: 'பூச்சி கட்டுப்பாடு',
    pestControlCardSubtitle: 'பூச்சிகளை கண்டறிந்து கட்டுப்படுத்துங்கள்',
    marketPricesCardTitle: 'சந்தை விலைகள்',
    marketPricesCardSubtitle: 'தற்போதைய விலைகளை பார்க்கவும்',
    weatherIn: 'இங்குள்ள வானிலை:',
    humidity: 'ஈரப்பதம்',
    rainfall: 'மழை',
    quickActions: 'வேகமான செயல்கள்',
    manageFarms: 'பண்ணைகளை நிர்வகிக்க',
    addNewFarm: 'புதிய பண்ணை சேர்க்க',
    yourFarms: 'உங்கள் பண்ணைகள்',
    noFarmsYet: 'இன்னும் பண்ணை சேர்க்கப்படவில்லை',
    addFirstFarmText: 'விளைச்சல் ஆலோசனைகள் பெற முதல் பண்ணையை சேர்க்கவும்',
    addFirstFarmButton: 'முதல் பண்ணையை சேர்க்கவும்',
    emailPlaceholder: 'மின்னஞ்சல் ஐடி அளிக்கவும்',
    passwordPlaceholder: 'கடவுச்சொல்லை அளிக்கவும்',
    fullNamePlaceholder: 'முழு பெயர்',
    emailAddressPlaceholder: 'மின்னஞ்சல் முகவரி',
    phoneNumberPlaceholder: 'தொலைபேசி எண்',
    selectDistrictPlaceholder: 'மாவட்டத்தை தேர்ந்தெடுக்கவும்',
    villagePlaceholder: 'கிராமம்/நகரம்',
    createPasswordPlaceholder: 'கடவுச்சொல்லை உருவாக்கவும்',
    languageEnglish: 'ஆங்கிலம்',
    languageMalayalam: 'மலையாளம்',
    languageTamil: 'தமிழ்',
    languageKannada: 'கன்னடம்',
    languageTulu: 'துலு',
    languageKonkani: 'கொங்கணி',
    languageHindi: 'இந்தி',
    languageUrdu: 'உருது',
    languageLabelShort: 'மொழி',
    // Farms
    farmsTitle: 'என் பண்ணைகள்',
    farmsSubtitle: 'உங்கள் விவசாய நிலங்களை நிர்வகிக்க',
    addFarmButton: 'பண்ணை சேர்க்க',
    editFarmTitle: 'பண்ணையை திருத்து',
    addNewFarmTitle: 'புதிய பண்ணை சேர்க்க',
    farmNameLabel: 'பண்ணையின் பெயர்',
    farmNamePlaceholder: 'பண்ணை பெயரை அளிக்கவும்',
    locationLabel: 'இடம்',
    locationPlaceholder: 'மாவட்டம், கிராமம்',
    cropTypeLabel: 'பயிர் வகை',
    cropTypePlaceholder: 'பயிரை தேர்ந்தெடுக்கவும் (விருப்பம்)',
    farmSizeLabel: 'பண்ணையின் அளவு',
    sizePlaceholder: 'அளவு',
    acres: 'ஏக்கர்',
    hectares: 'ஹெக்டேர்',
    cancel: 'ரத்து செய்',
    saving: 'சேமிக்கிறது...',
    saveFarm: 'பண்ணையை சேமிக்க',
    updateFarm: 'புதுப்பிக்க',
    addFarm: 'பண்ணை சேர்க்க',
    noFarmsAddedTitle: 'இன்னும் பண்ணை சேர்க்கப்படவில்லை',
    noFarmsAddedText: 'விவசாய ஆலோசனைகள் பெற முதல் பண்ணையை சேர்க்கவும்',
    addFirstFarmButtonFarms: 'முதல் பண்ணையை சேர்க்கவும்',
    deleteFarmConfirm: 'இந்த பண்ணையை நீக்க விரும்புகிறீர்களா?',
    // Crop Recommendations
    cropRecoTitle: 'பயிர் பரிந்துரைகள்',
    cropRecoSubtitle: 'உங்கள் பண்ணை நிலைக்கு ஏற்ப AI அடிப்படையிலான பயிர் பரிந்துரைகள்',
    farmConditions: 'பண்ணை நிலை',
    soilTypeLabel: 'மண் வகை',
    waterAvailabilityLabel: 'தண்ணீர் கிடைப்பாடு',
    districtOptionalLabel: 'மாவட்டம் (விருப்பம்)',
    districtPlaceholderReco: 'உங்கள் மாவட்டத்தின் பெயரை அளிக்கவும்',
    analyzeButton: 'பயிர் பரிந்துரைகள் பெற',
    analyzingText: 'பண்ணை நிலையை பகுப்பாய்வு செய்கிறது...',
    analyzingSpinnerText: 'உங்கள் பண்ணை நிலைகளை பகுப்பாய்வு செய்கிறது...',
    noRecoTitle: 'பரிந்துரைகள் எதுவும் கிடைக்கவில்லை',
    noRecoText: 'மண், தண்ணீர் போன்ற விவரங்களை மாற்றி மீண்டும் முயற்சிக்கவும்',
    recommendedCropsTitle: 'பரிந்துரைக்கப்பட்ட பயிர்கள்',
    seasonLabel: 'காலம்',
    waterLabel: 'தண்ணீர்',
    durationLabel: 'கால அளவு',
    yieldLabel: 'மொத்த மகசூல்',
    benefitsLabel: 'பலன்கள்:',
    suitabilityHigh: 'மிகவும் ஏற்றது',
    suitabilitySuitable: 'ஏற்றது',
    suitabilityModerate: 'சராசரி ஏற்றது',
    suitabilityLow: 'குறைந்த அளவு ஏற்றது',
    // Market Prices
    marketTitle: 'கேரள விவசாய சந்தை விலைகள்',
    marketSubtitle: 'கேரளாவின் பல சந்தைகளில் உள்ள நேரடி விவசாய விலைகள்',
    commoditiesLabel: 'பொருட்கள்',
    marketsLabel: 'சந்தைகள்',
    avgPriceLabel: 'சராசரி விலை',
    risingPricesLabel: 'உயரும் விலைகள்',
    filterPricesTitle: 'விலைகளை வடிகட்டி காண்க',
    searchLabel: 'பொருட்கள் மற்றும் சந்தைகளை தேடவும்',
    searchPlaceholder: 'அரி, தெங்காய், சந்தை பெயர்கள் போன்றவை தேடுங்கள்...',
    selectCommodityLabel: 'பொருளை தேர்ந்தெடுக்கவும்',
    allCommoditiesOption: 'அனைத்து பொருட்களும்',
    selectDistrictLabel: 'மாவட்டத்தை தேர்ந்தெடுக்கவும்',
    refreshPricesButton: 'விலைகளை புதுப்பிக்க',
    refreshingButton: 'புதுப்பிக்கிறது...',
    exportCsvButton: 'CSV ஆக ஏற்றுமதி செய்',
    clearFiltersButton: 'வடிகட்டுக்களை நீக்கு',
    marketTrendsTitle: 'சந்தை போக்குகள்',
    marketInsightTitle: 'சந்தை தகவல்:',
    marketInsightText:
      'அரசு APMC சந்தைகளிலிருந்து விலைகள் தினமும் புதுப்பிக்கப்படுகின்றன. சிறந்த விலை பெற அடிக்கடி பார்க்கவும்.',
    sellingTipsTitle: 'விற்கும் குறிப்புகள்',
    sellingTips1: 'காலை நேரத்தில் விற்பனை செய்தால் நல்ல விலை கிடைக்கும்',
    sellingTips2: 'பல சந்தை விலைகளை ஒப்பிட்டு பார்க்கவும்',
    sellingTips3: 'உங்கள் விளைச்சலை தரப்படுத்தி அதிக விலை பெறுங்கள்',
    sellingTips4: 'வாராந்திர விலை மாற்றங்களை கவனிக்கவும்',
    sellingTips5: 'அரசு கொள்முதல் திட்டங்களை பரிசீலிக்கவும்',
    marketPriceListTitle: 'சந்தை விலை பட்டியல்',
    showingCommoditiesText: 'காண்பிக்கப்படுகிறது',
    inText: 'இடம்:',
    dateLabel: 'தேதி',
    loadingMarketTitle: 'சந்தை விலைகள் ஏற்றப்படுகிறது',
    loadingMarketText: 'கேரள சந்தைகளிலிருந்து சமீபத்திய விலைகள் பெறப்படுகிறது...',
    commodityColumn: 'பொருள்',
    marketColumn: 'சந்தை',
    districtColumn: 'மாவட்டம்',
    priceRangeColumn: 'விலை வரம்பு',
    trendColumn: 'போக்கு',
    updatedColumn: 'புதுப்பிப்பு',
    perUnitText: 'ஒரு',
    noMarketDataText:
      'உங்கள் வடிகட்டல்களுக்கு பொருந்தும் சந்தை தரவு இல்லை. வடிகட்டலை மாற்றி மீண்டும் முயற்சிக்கவும்.',
    tableFooterSource: 'தரவு: Agmarknet & கேரள விவசாயத் துறை',
    tableFooterShowing: 'காண்பிக்கப்படுகிறது',
    tableFooterOf: 'மொத்தம்',
    tableFooterEntries: 'பதிவுகளில் இருந்து',
    refreshButton: 'புதுப்பி',
    dataSourcesTitle: 'தரவு மூலங்கள் & புதுப்பிப்புகள்',
    agmarknetStatus: 'Agmarknet API:',
    agmarknetConnected: 'இணைக்கப்பட்டுள்ளது',
    agmarknetOffline: 'ஆஃப்லைன்',
    updatesEvery: 'புதுப்பிப்பு: ஒவ்வொரு 5 நிமிடத்திற்கும்',
    coverageLabel: 'கவரேஜ்:',
    nextUpdateText: 'அடுத்த புதுப்பிப்பு 5 நிமிடங்களில்',
    priceAlertsTitle: 'விலை அலர்ட்',
    priceAlertsText: 'உங்கள் பயிர் இலக்கு விலையை அடைந்தால் அறிவிப்பு பெறுங்கள்',
    setPriceAlertButton: 'விலை அலர்ட் அமைக்க',
    priceAlertPrompt: 'விலை அலர்ட் அமைக்க:',
    priceAlertCurrent: 'தற்போதைய விலை',
    priceAlertEnterTarget: 'இலக்கு விலையை உள்ளிடவும் (₹ ஒரு கிலோக்கு):',
    priceAlertSuccess: 'விலை அலர்ட் வெற்றிகரமாக அமைக்கப்பட்டது!',
    nearestMarketsTitle: 'அருகிலுள்ள சந்தைகள்',
    nearestMarketsText: 'உங்கள் அருகிலுள்ள விவசாய சந்தைகளை கண்டறியவும்',
    viewMapButton: 'வரைபடம் காண்க',
    // Pest Management (Plant Health)
    plantIdOnline: 'Plant.id v3 AI ஆன்லைன்',
    plantIdOffline: 'மேம்பட்ட சிம்யுலேஷன் பயன்படுத்தப்படுகிறது',
    plantIdChecking: 'AI இணைப்பு சரிபார்க்கப்படுகிறது...',
    plantIdStatusOnline: 'நேரடி நோய் கண்டறிதல் செயலில் உள்ளது',
    plantIdStatusOffline: 'இமேஜ் அனாலிசிஸ் சிம்யுலேஷன் பயன்படுத்தப்படுகிறது',
    plantIdStatusChecking: 'Plant.id v3 API சரிபார்க்கப்படுகிறது...',
    aiScannerTitle: 'AI தாவர ஆரோக்கிய ஸ்கேனர்',
    aiScannerSubtitle: 'Plant.id v3 AI மூலம் பூச்சி மற்றும் நோய் கண்டறிதல்',
    uploadLeafTitle: 'இலையின் படத்தை பதிவேற்றவும்',
    uploadLeafSubtitle: 'உடனடி AI அடிப்படையிலான நோய் கண்டறிதல் மற்றும் சிகிச்சை பரிந்துரைகள்',
    aiAnalysisInProgress: 'AI பகுப்பாய்வு நடைபெறுகிறது...',
    captureOrUpload: 'இலையின் படத்தை எடுக்கவும் அல்லது பதிவேற்றவும்',
    bestResultsText:
      'சிறந்த முடிவுகளுக்கு: நல்ல வெளிச்சத்தில் படம் எடுக்கவும், பாதிக்கப்பட்ட பகுதியை தெளிவாகக் காட்டவும், பல இலைகளை சேர்க்கவும்',
    selectImageButton: 'படத்தை தேர்வுசெய்',
    analyzingWithAI: 'AI பயன்படுத்தி பகுப்பாய்வு செய்கிறது...',
    clearImageButton: 'படத்தை அழிக்கவும்',
    imagePreviewTitle: 'பட முன்னோட்டம்',
    readyForAI: 'AI பகுப்பாய்வுக்கு தயார்',
    simulationTitle: 'மேம்பட்ட சிம்யுலேஷன் பயன்படுத்தப்படுகிறது',
    simulationMessage: 'API இணைப்பு சிக்கல் - உள்ளூர் பகுப்பாய்வு பயன்படுத்தப்படுகிறது',
    technicalInfoTitle: 'தொழில்நுட்ப தகவல்:',
    technicalInfoOnline: 'Plant.id v3 API மூலம் உண்மையான கண்டறிதல்',
    technicalInfoOffline: 'இமேஜ் அனாலிசிஸுடன் மேம்பட்ட சிம்யுலேஷன்',
    diseaseDetectedTitle: 'நோய் கண்டறியப்பட்டது',
    plantHealthyTitle: 'தாவரம் ஆரோக்கியமாக உள்ளது',
    aiConfidenceLabel: 'AI நம்பிக்கை சதவீதம்',
    diagnosisDetailsTitle: 'நோய் விவரங்கள்',
    scientificClassificationTitle: 'அறிவியல் வகைப்படுத்தல்',
    treatmentTitle: 'சிகிச்சை பரிந்துரைகள்',
    treatmentFooter: 'முதல் அறிகுறிகள் தென்பட்டவுடன் சிகிச்சையைத் தொடங்கவும்',
    preventionTitle: 'தடுப்பு நடவடிக்கைகள்',
    careRecoTitle: 'தாவர பராமரிப்பு பரிந்துரைகள்',
    analyzeAnotherImageButton: 'மற்றொரு படத்தை பகுப்பாய்வு செய்ய',
    poweredByPlantIdTitle: 'Plant.id v3 API மூலம் இயக்கப்படுகிறது',
    poweredByPlantIdText:
      'லட்சக்கணக்கான தாவர படங்களைக் கொண்டு பயிற்சி செய்யப்பட்ட மேம்பட்ட மெஷின் லெர்னிங் மாதிரிகள்',
    aiPoweredTitle: 'AI இயக்கப்படுகிறது',
    aiPoweredText: 'Plant.id v3 நியூரல் நெட்வொர்க் பயன்படுத்துகிறது',
    globalDatabaseTitle: 'உலகளாவிய தரவுத்தளம்',
    globalDatabaseText: 'ஆயிரக்கணக்கான தாவர இனங்கள்',
    realtimeTitle: 'நேரடி',
    realtimeText: 'உடனடி பகுப்பாய்வு மற்றும் முடிவுகள்',
    plantIdFooter: 'தாவர நோய் கண்டறிதலுக்கு Plant.id v3 API பயன்படுத்தப்படுகிறது',
    // Chatbot
    chatbotFloatingTooltip: 'விவசாய உதவியாளர்',
    chatbotHeaderTitle: 'விவசாய உதவியாளர்',
    chatbotHeaderSubtitle: 'AI மூலம் இயக்கப்படுகிறது',
    chatbotQuickQuestionsTitle: 'விரைவான கேள்விகள்:',
    chatbotQuick1: 'இந்த காலத்திற்கு சிறந்த பயிர்கள் என்ன?',
    chatbotQuick2: 'நெல் வயலில் பூச்சி கட்டுப்பாடு?',
    chatbotQuick3: 'ஆர்கானிக் விவசாய திட்டங்கள்',
    chatbotQuick4: 'தேங்காய் விவசாய குறிப்புகள்',
    chatbotQuick5: 'வானிலை அடிப்படையிலான ஆலோசனை',
    chatbotQuick6: 'சந்தை விலைகள்',
    chatbotThinking: 'யோசிக்கிறது...',
    chatbotPlaceholder: 'கேரளாவில் விவசாயம் பற்றி ஏதும் கேளுங்கள்...',
    chatbotClear: 'அழிக்கவும்',
    chatbotPressEnter: 'செய்தி அனுப்ப Enter அழுத்தவும்',
    chatbotError: 'மன்னிக்கவும், தொழில்நுட்ப சிக்கல் ஏற்பட்டுள்ளது. தயவு செய்து பின்னர் முயற்சிக்கவும்.',
    chatbotGreeting:
      "வணக்கம்! 🙏 நான் உங்கள் கேரள விவசாய AI உதவியாளர், Google Gemini AI மூலம் இயக்கப்படுகிறேன். கேரள விவசாயிகளுக்கான துல்லியமான விவசாயத் தகவலை வழங்குவதே என் நோக்கம்.\n\nஇன்று கேரள விவசாயம் பற்றி நீங்கள் என்ன அறிய விரும்புகிறீர்கள்?",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key) => translations[language][key] || key,
    }),
    [language]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);


